lang: en
project:
  type: book
  output-dir: docs
  resources: resources
execute:
  freeze: auto
lightbox: true
book:
  title: Analysis
  subtitle: ''
  author:
    - orcid: 0000-0002-2135-6888
      name:
        family: Mahrholz
        given: Gaby
    - orcid: 0000-0003-0830-7915
      name:
        family: Kuepper-Tetzel
        given: Carolina E.
  doi: ''
  license: CC-BY
  description: Data skills book for Level 2 Psychology students at the School of Psychology and Neuroscience at the University of Glasgow
  cover-image: images/logos/logo_analysis.png
  image: images/logos/logo_analysis.png
  favicon: images/logos/logo_analysis.png
  cookie-consent: false
  page-navigation: true
  search: true
  sharing:
  - twitter
  - facebook
  - linkedin
  sidebar:
    title: ''
    logo: ''
    search: true
    contents: ''
    style: floating
    background: light
    foreground: dark
    border: true
    alignment: left
    collapse-level: 3
    pinned: true
    header: ''
    footer: ''
  margin-header: margin-header.html
  page-footer: CC-BY (2025) Gaby Mahrholz Carolina E. Kuepper-Tetzel
  chapters:
  - index.qmd
  - part: "INDIVIDUAL WALKTHROUGH CHAPTERS"
    chapters:
    - 01-basics.qmd
    - 02-wrangling.qmd
    - 03-wrangling2.qmd
    - 04-dataviz.qmd
    - 05-dataviz2.qmd
    - 06-chi-square-one-sample.qmd
    - 07-independent.qmd
    - 08-paired.qmd
    - 09-correlation.qmd
    - 10-regression.qmd
    - 11-multiple-regression.qmd
    - 12-one-way-anova.qmd
    - 13-factorial-anova.qmd
  - part: "IN-LAB: PAIR-CODING"
    chapters: 
    - pc-A01.qmd
    - pc-A02.qmd
    - pc-A03.qmd
    - pc-A04.qmd
    - pc-A05.qmd
    - pc-A06.qmd
    - pc-A07.qmd
    - pc-B01.qmd
    - pc-B02.qmd
    - pc-B03.qmd
    - pc-B04.qmd
    - pc-B05.qmd
    - pc-B06.qmd
  appendices:
  - appendix-a-installing-r.qmd
  - appendix-b-updating-packages.qmd
  - appendix-d-symbols.qmd
  - appendix-x-How-to-cite-R.qmd
  - appendix-y-license.qmd
bibliography: include/references.bib
csl: include/apa.csl
format:
  html:
    link-external-icon: false
    theme:
      light:
      - flatly
      - include/light.scss
      dark:
      - darkly
      - include/dark.scss
    css:
    - https://use.fontawesome.com/releases/v5.13.0/css/all.css
    - include/booktem.css
    - include/webex.css
    - include/glossary.css
    - include/style.css
    - include/custom.scss
    - include/styles.css
    df-print: kable
    code-link: true
    code-fold: false
    code-line-numbers: true
    code-overflow: wrap
    code-copy: hover
    highlight-style: a11y
    mainfont: ''
    monofont: ''
    include-after-body:
    - include/webex.js
    - include/script.js
