# Overview {.unnumbered}


This course covers data skills R Markdown, data wrangling, and data visualisation. This book also introduces learners to the most common statistical analyses such as t-test, correlations, regressions, and ANOVAs. The main idea of this book is being reproducible in our data analysis approach. 


### How To Use This Book {.unnumbered}

Each chapter in the book has the same structure: 

1. **Individual walkthrough**: Complete this section at your own pace. Take your time to complete the guided activities. Plan for time pockets in your week to work through this section. 
2. **Pair coding**: During the lab we are reserving time for you to work through activities with a peer. If you get stuck, try to solve the issue. A GTA and your tutor will be available to help you, too. Note: We have added a pair coding activity to every chapter in the book - even for chapters that are not associated with a lab. Feel free to get together with a peer to complete the tasks. 
3. **Test your knowledge**: The final section in each chapter is a short quiz that assesses your knowledge and skills covered in the chapter. 


To support you to work through the book chapters continuously, we have scheduled each chapter so that it aligns as well as possible with the stats lectures and the lab content. We also made sure that no chapters are scheduled during busy assessment times (such as during the run-up to the research report deadline). You will have chapters in weeks 1-5 and then again weeks 9-11. 

If you get stuck, seek help during your lab, GTA or PAL support sessions, and/or by posting on the Data Skills and R channel on Teams. 



### Statement on use of AI {.unnumbered}

ChatGPT 4.0 was used to assist in the writing of these materials in the following ways:

* To suggest multiple-choice questions in the "Test your knowledge and challenge yourself" section
* To proof-read and check for typos
* To suggest improvements to the text

Any information provided by ChatGPT was verified, for example, where code was used, the syntax and output was checked to ensure it was correct and where theoretical or conceptual information was provided, only that which the author could verify from their pre-existing expertise was included. 





**Note & Contact**: This book is currently being updated which means that chapters are being published on a rolling basis. We regularly check and update for improvements. If you have any feedback or suggestions, please submit them to our [Analysis R Book Improvement form](https://forms.office.com/e/qsZCBmduJB){target="_blank"}. For people outwith University of Glasgow: You are welcome to share feedback by emailing [Gaby Mahrholz](mailto:gaby.mahrholz@glasgow.ac.uk). 

**Acknowledgement of previous versions**: This version of the book was adapted from a previous version written by Phil McAleer, Carolina E. Kuepper-Tetzel, & Helena M. Paterson



```{r, echo=FALSE}
version <- R.version.string
nickname <- R.version$nickname
```

**R Version:** This book has been written with `r version` (`r nickname`) and RStudio version 2023.12.1+402 "Ocean Storm".

