{
  "hash": "5d9202e6966082a144b2b43a85220c9b",
  "result": {
    "markdown": "# Paired t-test {#sec-paired}\n\n\n\n\n\n## Intended Learning Outcomes {.unnumbered}\n\nBy the end of this chapter you should be able to:\n\n- Compute a paired t-test and effectively report the results.\n- Understand when to use a non-parametric equivalent of the paired t-test, compute it, and report the results.\n\n\n\n## [Individual Walkthrough]{style=\"color: #F39C12; text-transform: uppercase;\"} {.unnumbered}\n\n## Activity 1: Setup\n\nIn this chapter, we will continue working with the dataset from the study by Zwaan et al. (2018). Have a look at @sec-independent or the SupMats document if you need a refresher on the Simon Task data.\n\n* Open last week's project\n* Create a new `.Rmd` file and save it to your project folder\n* Delete everything after the setup code chunk (e.g., line 12 and below) \n\n\n\n## Activity 2: Library and data for today\n\nToday, we will need the following packages `rstatix`, `tidyverse`, `qqplotr`, `lsr`, and `pwr`. You should have all the necessary packages installed from previous chapters already. If not, you can install them via the console (see @sec-install_packages for more details).\n\nAgain, load the `rstatix` package before `tidyverse`. Then read in the data from `MeansSimonTask.csv` and the demographics information from `DemoSimonTask.csv`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load in the packages\n???\n\n# read in the data\nzwaan_data <- ???\nzwaan_demo <- ???\n```\n:::\n\n\n\n\n\n\n\n::: {.callout-caution collapse=\"true\" icon=\"false\"} \n\n## Solution \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load in the packages\nlibrary(rstatix)\nlibrary(tidyverse)\nlibrary(qqplotr)\nlibrary(lsr)\nlibrary(pwr)\n\n# read in the data\nzwaan_data <- read_csv(\"MeansSimonTask.csv\")\nzwaan_demo <- read_csv(\"DemoSimonTask.csv\")\n```\n:::\n\n\n:::\n\n\nAs usual, take some time to familiarise yourself with the data before starting the within-subjects t-test.\n\nToday, we will focus on the Simon effect itself. Remember that the Simon effect predicts shorter response times for congruent trials compared to incongruent trials. Therefore, we are inclined to propose a directional hypothesis.\n\n\n* **Potential research question**: \"Is there a significant difference in response times between congruent and incongruent trials in a Simon task?\"\n* **Null Hypothesis (H~0~)**: \"There is no significant difference in response times between congruent and incongruent trials in a Simon task.\"\n* **Alternative Hypothesis (H~1~)**: \"Response times for congruent trials are significantly shorter than those for incongruent trials in a Simon task.\" or phrased differently \"Participants will respond significantly faster in congruent trials than in incongruent trials in a Simon task.\"\n\n## Activity 3: Preparing the dataframe\n\nAgain, we need to **calculate the mean response time (RT) for both congruent and incongruent trials per participant**. As we did last week, we can also **compute the Simon effect** as the difference score between incongruent and congruent trials.\n\n::: {.callout-tip}\nTo keep all the data in one place, we should join this output with the demographics. While you won’t need the demographic information for the t-test itself, having it included will give you a complete dataframe. This can be useful when you need to calculate demographics for the Methods section; for example if you end up excluding data points, you can compute sample size, age, and gender splits straight away rather than having to apply the same exclusion criteria to a different data object.\n:::\n\nFor the paired version of the `t.test`, we need the congruent and incongruent trials in separate columns, ensuring **each participant still has only one row in the dataframe** (i.e., **wide format**). Below is the output we aim to achieve:\n\n\n::: {.cell}\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|participant |gender | age|education          |similarity | congruent| incongruent| simon_effect|\n|:-----------|:------|---:|:------------------|:----------|---------:|-----------:|------------:|\n|T1          |Female |  50|High school        |same       |  475.0032|    508.2835|     33.28029|\n|T10         |Male   |  45|Associate's degree |same       |  420.1515|    401.5800|    -18.57148|\n|T109        |Male   |  33|Bachelor's degree  |same       |  339.5343|    375.7152|     36.18085|\n|T11         |Female |  71|High school        |same       |  516.9722|    542.3111|     25.33889|\n|T111        |Female |  34|High school        |same       |  373.5778|    394.0665|     20.48874|\n\n</div>\n:::\n:::\n\n\n::: {.callout-note icon=\"false\"}\n\n## Your Turn\n\nChallenge yourself! Try recreating the table without hints this time. *(Note: The table above is abbreviated; your data object should include the data from ALL participants.)*\n\n\n::: {.callout-caution collapse=\"true\" icon=\"false\"}\n\n## Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsimon_effect <- zwaan_data %>% \n  pivot_longer(cols = session1_congruent:session2_incongruent, names_to = \"col_headings\", values_to = \"RT\") %>% \n  separate(col_headings, into = c(\"Session_number\", \"congruency\"), sep = \"_\") %>% \n  group_by(participant, similarity, congruency) %>% \n  summarise(mean_RT = mean(RT)) %>% \n  ungroup() %>% \n  pivot_wider(names_from = congruency, values_from = mean_RT) %>% \n  mutate(simon_effect = incongruent - congruent) %>% \n  full_join(zwaan_demo, by = join_by(participant == twosubjectnumber)) %>% \n  select(participant, gender = gender_response, age = age_response, education = education_response, similarity:simon_effect)\n```\n:::\n\n\n:::\n\n::: {.callout-tip collapse=\"true\"}\n\n## You could have also...\n\n1. looked at the hints from the last chapter, since we are working with the exact same dataframe today.\n2. saved the data object from last week as a csv file and read it in here.\n\n:::\n\n:::\n\n\n## Activity 4: Compute descriptives\n\nWe want to compute means and standard deviations for both the `congruent` and the `incongruent` trials. Then, we will subtract the mean RT of the congruent trials from the mean RT of the incongruent trials to calculate the average difference score between the two conditions.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndescriptives <- simon_effect %>% \n  summarise(mean_congruent = mean(congruent),\n            sd_congruent = sd(congruent),\n            mean_incongruent = mean(incongruent),\n            sd_incongruent = sd(incongruent),\n            diff = mean_incongruent - mean_congruent, # diff = mean(simon_effect) would also work\n            sd_diff = sd(simon_effect))\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| mean_congruent| sd_congruent| mean_incongruent| sd_incongruent|     diff|  sd_diff|\n|--------------:|------------:|----------------:|--------------:|--------:|--------:|\n|       427.6528|     74.17418|         462.0785|       74.69692| 34.42571| 21.59876|\n\n</div>\n:::\n:::\n\n\n\n::: {.callout-note}\n\nNotice that we did not have to use `group_by()` here because the data is already in wide format.\n\n:::\n\n\n## Activity 5: Create an appropriate plot\n\n### Option 1: congruent and incongruent trials\n\nTo create an appropriate plot, we need the data in long format. This format should include a `congruency` column containing the labels for congruent and incongruent trials, and a `mean_RT` column to store the corresponding mean response times. **Each participant should now have two rows in the dataset.**\n\n\n::: {.cell}\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|participant |gender | age|education          |similarity | simon_effect|congruency  |  mean_RT|\n|:-----------|:------|---:|:------------------|:----------|------------:|:-----------|--------:|\n|T1          |Female |  50|High school        |same       |     33.28029|congruent   | 475.0032|\n|T1          |Female |  50|High school        |same       |     33.28029|incongruent | 508.2835|\n|T10         |Male   |  45|Associate's degree |same       |    -18.57148|congruent   | 420.1515|\n|T10         |Male   |  45|Associate's degree |same       |    -18.57148|incongruent | 401.5800|\n|T109        |Male   |  33|Bachelor's degree  |same       |     36.18085|congruent   | 339.5343|\n\n</div>\n:::\n:::\n\n\n\n::: {.callout-note icon=\"false\"} \n\n## Your Turn\n\nFirst, wrangle data into long format. The first 5 rows should match the output above. Then, use this table to create an appropriate plot that visualises the differences in mean response times between congruent and incongruent trials.\n\n::: {.callout-caution collapse=\"true\" icon=\"false\"} \n\n## Solution for the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsimon_effect_long <- simon_effect %>% \n  pivot_longer(cols = c(congruent, incongruent), names_to = \"congruency\", values_to = \"mean_RT\")\n```\n:::\n\n\n\n:::\n\n\n::: {.callout-caution collapse=\"true\" icon=\"false\"} \n\n## Solution for the plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(simon_effect_long, aes(x = congruency, y = mean_RT, fill = congruency)) +\n  geom_violin(alpha = 0.5) +\n  geom_boxplot(width = 0.4, alpha = 0.8) +\n  scale_fill_viridis_d(guide = \"none\") +\n  theme_classic() +\n  labs(x = \"Congruency\", y = \"mean Response Time\")\n```\n\n::: {.cell-output-display}\n![](08-paired_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n:::\n\n:::\n\n### Option 2: difference scores between congruent and incongruent trials\n\nWe could have displayed the difference scores between the two conditions directly. This approach would use the `simon_effect` object without requiring additional data wrangling, as the difference scores are already stored in the `simon_effect` column.\n\n::: {.callout-note collapse=\"true\" icon=\"false\"} \n\n## Hints for the plot\n\nWe want to create a violin-boxplot, but this time it will have only one value on the x-axis instead of a grouping variable as we usually include. This causes the `ggplot()` function to behave slightly differently. Specifically, you would leave the x-value blank.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data, aes(x = \"\", y = continuous_variable)) +\n```\n:::\n\n\n\nTo add colour, use the usual arguments (e.g., `fill`, `colour`), but specify them within the `geom_` functions instead of `ggplot()`, as we typically do.\n\n:::\n\n::: {.callout-caution collapse=\"true\" icon=\"false\"} \n\n## Solution for the plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(simon_effect, aes(x = \"\", y = simon_effect)) +\n  geom_violin(fill = \"#A3319F\", alpha = 0.5) +\n  geom_boxplot(fill = \"#A3319F\", width = 0.4) +\n  theme_classic() +\n  labs(x = \"\",\n       y = \"Difference in mean Response Time scores\")\n```\n\n::: {.cell-output-display}\n![](08-paired_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n:::\n\n## Activity 6: Check assumptions\n\nThe assumptions for a paired t-test are fairly similar to the one-sample t-test.\n\n#### Assumption 1: Continuous DV {.unnumbered}\n\nThe dependent variable needs to be measured at interval or ratio level. We can confirm that by looking at either the columns `congruent` and `incongruent` in the object `simon_effect`. Or the variable `mean_RT` in `simon_effect_long`. This assumption holds.\n\n\n#### Assumption 2: Data are independent {.unnumbered}\n\nFor a paired t-test this assumption applies to the **pair of values**, i.e., each pair of values needs to be from a separate participant. We assume this assumption holds for our data.\n\n\n\n#### Assumption 3: Normality {.unnumbered}\n\nThis assumption requires the **difference scores** to be approximately normally distributed. We cannot see that from the violin-boxplot above (Option 1) and have to plot the difference score, i.e., variable `simon_effect`.\n\n::: {.callout-note icon=\"false\"} \n\n## Your Turn\n\nPlot the difference score.\n\n::: {.callout-note collapse=\"true\" icon=\"false\"} \n\n## Hint\n\nThink back to the one-sample t-test. How did we plot the normality assumption there?\n\n:::\n\n::: {.callout-caution collapse=\"true\" icon=\"false\"} \n\n## Solution\n\nExplore the three possible approaches in the tabs below.\n\n::: {.panel-tabset}\n\n## Option 1: Q-Q plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(simon_effect, aes(sample = simon_effect)) +\n  stat_qq_band(fill = \"#FB8D61\", alpha = 0.4) +\n  stat_qq_line(colour = \"#FB8D61\") +\n  stat_qq_point()\n```\n\n::: {.cell-output-display}\n![](08-paired_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n\n## Option 2: Violin-boxplot of the difference score\n\nYou can use the plot from above if you chose Option 2 in Activity 5, or create a new violin-boxplot if you created plot Option 1 above.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(simon_effect, aes(x = \"\", y = simon_effect)) +\n  geom_violin(fill = \"#FB8D61\", alpha = 0.5) + # alpha for opacity, fill for adding colour\n  geom_boxplot(fill = \"#FB8D61\", width = 0.4) + # change width of the boxes\n  theme_classic() +\n  labs(x = \"\",\n       y = \"Difference in mean Response Time scores\")\n```\n\n::: {.cell-output-display}\n![](08-paired_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n\n## Option 3: Shapiro-Wilk test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(simon_effect$simon_effect)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tShapiro-Wilk normality test\n\ndata:  simon_effect$simon_effect\nW = 0.98588, p-value = 0.1047\n```\n:::\n:::\n\n:::\n\nBoth plots suggest slight deviations from normality in the tails, which are not detected by the Shapiro-Wilk test. However, minor deviations from normality are acceptable for t-tests, especially in the tails of the distribution. Therefore, we conclude that the difference scores are approximately normally distributed.\n\n:::\n\n\n:::\n\n\n::: {.callout-note} \n\n\nAssessing normality is never as straightforward as it appears in textbooks. While idealised examples often depict perfectly symmetrical bell curves, real-world data rarely aligns with such precision. Instead, normality exists \"on a spectrum\", and it is your responsibility to evaluate whether the data’s shape is sufficiently close to normal for the purposes of your analysis.\n\nThis evaluation requires either visual inspection or relying on statistical tests. However, as pointed out in previous chapters, both approaches have limitations and neither provides an absolute answer. Instead of seeking perfection, focus on whether any deviations from normality meaningfully impact the validity of your results.\n\n:::\n\n\n**If any of the assumptions are violated, use the non-parametric equivalent to the paired t-test, see @sec-alternative_paired.**\n\n\n\n\n## Activity 7: Compute a paired t-test and effect size\n\nWe can use the `t.test()` function again to compute the paired t-test. However, we are stuck with the BaseR pattern `data$column` once more. \n\n::: {.callout-note collapse=\"true\"} \n## Rant about BaseR and reminiscing about the \"good old days\"\n\nIn case you haven't picked it up by now, I am not much a fan of `data$column` (i.e., wide format) and prefer the `DV ~ IV` (i.e., long format) pattern. And there was a time when the `t.test()` function allowed to add an extra argument `paired = TRUE` to the *formula version* but that is no longer the case. 😭😭😭 Now, the argument *only* works on the default method, specifying arguments x and y separately. And because the default version doesn't allow us to add a `data = ` argument, we have to revert to `data$column`.\n\nPS: Carolina disagrees with me and prefers some BaseR every now and then. And that's totally fine, too - different researchers and coders have their own preferences, which you may have already noticed in the way you code.\n:::\n\nLong story short, here are the arguments you need from the data object in wide format (in this case data object `simon_effect`):\n\n* `data$column` for condition 1\n* `data$column` for condition 2\n* the extra argument `paired = TRUE` to tell the function we are conducting a paired rather than a two-sample t-test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(simon_effect$congruent, simon_effect$incongruent, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPaired t-test\n\ndata:  simon_effect$congruent and simon_effect$incongruent\nt = -20.161, df = 159, p-value < 2.2e-16\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n -37.79808 -31.05334\nsample estimates:\nmean difference \n      -34.42571 \n```\n:::\n:::\n\n\nThe output tells us pretty much what we need to know:\n\n* the test that was conducted (here a paired t-test),\n* the conditions that were compared (here congruent and incongruent), \n* the t-value, degrees of freedom, and a p-value,\n* the alternative hypothesis, \n* a 95% confidence interval,\n* and the mean difference score between both conditions (which also matches with our descriptives above).\n\n\nThe `t.test()` function does not give us an **effect size**, so, again, we have to compute it ourselves. We can use the `CohensD()` function from the `lsr` package as we did for the one-sample and the two-sample t-test. We can use the formula approach here as well, and add the extra argument `method = \"paired\"`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncohensD(simon_effect$congruent, simon_effect$incongruent, method = \"paired\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.593874\n```\n:::\n:::\n\n\n::: {.callout-tip}\n\nThe `cohensD()` function would also take a long format formula approach, such as from `simon_effect_long`, but you would need to make sure that the data within the columns are ordered correctly, i.e., Participant 1: condition 1, condition 2; Participant 2: condition 1, condition 2; etc. If that's not the case, then your results will be wrong. R helpfully provides a warning message for you to notice and double-check your data accordingly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncohensD(mean_RT ~ congruency, data = simon_effect_long, method = \"paired\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in cohensD(mean_RT ~ congruency, data = simon_effect_long, method =\n\"paired\"): calculating paired samples Cohen's d using formula input. Results\nwill be incorrect if cases do not appear in the same order for both levels of\nthe grouping factor\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.593874\n```\n:::\n:::\n\n:::\n\n## Activity 8: Sensitivity power analysis\n\nAs with the other t-test, we are conducting a sensitivity power analysis to determine the minimum effect size detectable with the number of participants we have in our sample (here n = 160), alpha of 0.05 and power of 0.8. This will tell us if our analysis was sufficiently powered or not.\n\nThe function we will use again is `pwr.t.test()` from the `pwr` package. The arguments in the formula are the same as for the one-sample t-test; we just need to adjust the number of participants and set the type to \"paired\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\npwr.t.test(n = 160, sig.level = 0.05, power = 0.8, type = \"paired\", alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n     Paired t test power calculation \n\n              n = 160\n              d = 0.222858\n      sig.level = 0.05\n          power = 0.8\n    alternative = two.sided\n\nNOTE: n is number of *pairs*\n```\n:::\n:::\n\n\nThe minimum effect size we could reliably detect is 0.22. Our actual effect size was 1.59, so this analysis was sufficiently powered. YAY\n\n## Activity 9: The write-up\n\nWe hypothesised that there would be a significant difference in the response times between congruent $(M = 427.65 msec, SD = 74.17 msec)$ and incongruent trials $(M = 462.08 msec, SD = 74.70 msec)$ of a Simon task. On average, participants were faster in the congruent compared to the incongruent condition $(M_{diff} = 34.43 msec, SD_{diff} = 21.60 msec)$. Using a within-subjects t-test, the effect was found to be significant and of a large magnitude, $t(159) = 20.16, p < .001, d = 1.59$. Therefore, we reject the null hypothesis in favour of H~1~.\n\n\n## Activity 10: Non-parametric alternative {#sec-alternative_paired}\n\n\nThe **Wilcoxon signed-rank test** is the non-parametric equivalent to the paired t-test, comparing the difference between the median for two measurements. \n\nBefore we compute the test, we need to determine some **summary stats** (e.g., here we focus on the median scores) for the congruent and incongruent conditions. Similar to the One-sample Wilcoxon signed-rank test, we can use the `summary()` function again because our data is in wide format.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(simon_effect)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n participant           gender               age         education        \n Length:160         Length:160         Min.   :19.00   Length:160        \n Class :character   Class :character   1st Qu.:30.75   Class :character  \n Mode  :character   Mode  :character   Median :37.00   Mode  :character  \n                                       Mean   :39.86                     \n                                       3rd Qu.:49.00                     \n                                       Max.   :71.00                     \n  similarity          congruent      incongruent     simon_effect   \n Length:160         Min.   :290.0   Min.   :324.9   Min.   :-18.57  \n Class :character   1st Qu.:379.4   1st Qu.:413.9   1st Qu.: 21.62  \n Mode  :character   Median :411.3   Median :449.7   Median : 34.77  \n                    Mean   :427.7   Mean   :462.1   Mean   : 34.43  \n                    3rd Qu.:458.7   3rd Qu.:496.3   3rd Qu.: 46.22  \n                    Max.   :741.5   Max.   :727.9   Max.   :103.84  \n```\n:::\n:::\n\n\nNow we can move on to the **Wilcoxon signed-rank test**. We will use the `wilcox.test()` function again, but add the argument `paired = TRUE`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwilcox.test(simon_effect$congruent, simon_effect$incongruent, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWilcoxon signed rank test with continuity correction\n\ndata:  simon_effect$congruent and simon_effect$incongruent\nV = 144, p-value < 2.2e-16\nalternative hypothesis: true location shift is not equal to 0\n```\n:::\n:::\n\n\n\n::: {.callout-note} \n\nWe could have also run a **One-sample Wilcoxon signed-rank test** on the difference score, but instead of comparing that to a population median (as we did in @sec-alternative_one_sample), we would compare it to 0 to assess whether the median difference between paired observations is significantly different from zero.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwilcox.test(simon_effect$simon_effect, mu = 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWilcoxon signed rank test with continuity correction\n\ndata:  simon_effect$simon_effect\nV = 12736, p-value < 2.2e-16\nalternative hypothesis: true location is not equal to 0\n```\n:::\n:::\n\n\n\n::: {.callout-important} \n\n## The V values are different between the 2 approaches - Does that matter?\n\nYes and no. The order in which you input variables into the function will affect the value of V - has to do with how the ranks are getting assigned. In our column `simon_effect` we subtracted congruent RT from incongruent RT. To have the exact equivalent, we will need to switch the columns in the `wilcox.test()` function. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nwilcox.test(simon_effect$incongruent, simon_effect$congruent, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWilcoxon signed rank test with continuity correction\n\ndata:  simon_effect$incongruent and simon_effect$congruent\nV = 12736, p-value < 2.2e-16\nalternative hypothesis: true location shift is not equal to 0\n```\n:::\n:::\n\n\nAnd as you can see, the V values match now.\n\n:::\n\n:::\n\nWe should also compute the **standardised test statistic Z**. Again, we need to calculate Z manually, using the qnorm function on the halved p-value from our Wilcoxon test above.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# storing the p-value\np_wilcoxon <- wilcox.test(simon_effect$incongruent, simon_effect$congruent, paired = TRUE)$p.value\n\n# calculate the z value from half the p-value\nz = qnorm(p_wilcoxon/2)\nz\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -10.72532\n```\n:::\n:::\n\n\n\nTo calculate an **effect size**, we would need to use the function `wilcox_effsize()` from the `rstatix` package. Unlike, the `wilcox.test()` and the `t.test()` function, `wilcox_effsize()` expects data to be in **long format** to be able to use the `DV ~ IV` pattern. Fortunately, we still have that available in `simon_effect_long`. We also need to add the argument `paired = TRUE`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwilcox_effsize(data = simon_effect_long, formula = mean_RT ~ congruency, paired = TRUE)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|.y.     |group1    |group2      |   effsize|  n1|  n2|magnitude |\n|:-------|:---------|:-----------|---------:|---:|---:|:---------|\n|mean_RT |congruent |incongruent | 0.8479786| 160| 160|large     |\n\n</div>\n:::\n:::\n\n\nNow we have all the numbers to **write this up**:\n\nA Wilcoxon signed-rank test was conducted to determine whether there was a significant difference in response times between congruent $(Mdn = 411.3 msec)$ and incongruent trials $(Mdn = 449.7 msec)$ in a Simon task. Median response times of Congruent trials were significantly faster $(Mdn = 34.77 msec)$ than incongruent trials, $Z = -10.73, p < .001, r = .848$. The difference can be classified as large according to Cohen (1992). Therefore, we reject the null hypothesis in favour of H~1~.\n\n\n\n## [Pair-coding]{style=\"color: #F39C12; text-transform: uppercase;\"} {.unnumbered}\n\n::: {.callout-important}\n\nThis week's pair-coding activity mirrors the one from @sec-independent. While there is no lab scheduled this week, I wanted to provide an opportunity for you to practice. You can treat this either as a \"Challenge Yourself\" activity or get together with friends to work through it together.\n\n:::\n\n### Task 1: Open the R project for the lab {.unnumbered}\n\n### Task 2: Create a new `.Rmd` file {.unnumbered}\n\n... and name it something useful. If you need help, have a look at @sec-rmd.\n\n### Task 3: Load in the library and read in the data {.unnumbered}\n\nThe data should already be in your project folder. If you want a fresh copy, you can download the data again here: [data_pair_coding](data/data_pair_coding.zip \"download\").\n\nWe are using the packages `rstatix`, `tidyverse`, `qqplotr`, `lsr` today.\nMake sure to load `rstatix` in before `tidyverse`.\n\nWe also need to read in `dog_data_clean_wide.csv`. Again, I've named my data object `dog_data_wide` to shorten the name but feel free to use whatever object name sounds intuitive to you. \n\nFor the plot, we will need the data in long format. We can either read in `dog_data_clean_long.csv` to take a shortcut, or wrangle the data from `dog_data_wide`. I've taken the shortcut and named my data object `dog_data_long`.\n\n\n\n\n::: {.cell}\n\n:::\n\n\n### Task 4: Tidy data for a paired t-test {.unnumbered}\n\nNot much tidying to do for today. \n\nPick a variable of interest and select the pre- and post-scores, and calculate the difference score. Store them in a separate data object with a meaningful name.\n\nI will use Loneliness as an example and call my data object `dog_lonely`. Regardless of your chosen variable, your data object should look like/ similar to the table below. \n\n\n::: {.cell}\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| RID| Loneliness_pre| Loneliness_post| Loneliness_diff|\n|---:|--------------:|---------------:|---------------:|\n|   1|           2.25|            1.70|           -0.55|\n|   2|           1.90|            1.60|           -0.30|\n|   3|           2.25|            2.25|            0.00|\n|   4|           1.75|            2.05|            0.30|\n|   5|           2.85|            2.70|           -0.15|\n\n</div>\n:::\n:::\n\n\nIn `dog_data_long`, we want to turn `Stage` into a factor so we can re-order the labels (i.e., \"pre\" before \"post\").\n\n\n::: {.callout-caution collapse=\"true\" icon=\"false\"}\n\n## Solution for Tasks 3 and 4\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Task 3\nlibrary(rstatix)\nlibrary(tidyverse)\nlibrary(lsr)\n\ndog_data_wide <- read_csv(\"data/dog_data_clean_wide.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nRows: 284 Columns: 24\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr  (3): GroupAssignment, Year_of_Study, Live_Pets\ndbl (21): RID, Age_Yrs, Consumer_BARK, Flourishing_pre, Flourishing_post, PA...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n:::\n\n```{.r .cell-code}\ndog_data_long <- read_csv(\"data/dog_data_clean_long.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nRows: 568 Columns: 16\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr  (4): GroupAssignment, Year_of_Study, Live_Pets, Stage\ndbl (12): RID, Age_Yrs, Consumer_BARK, Flourishing, PANAS_PA, PANAS_NA, SHS,...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n:::\n\n```{.r .cell-code}\n## Task 4\ndog_lonely <- dog_data_wide %>% \n  select(RID, Loneliness_pre, Loneliness_post) %>% \n  mutate(Loneliness_diff = Loneliness_post - Loneliness_pre)\n\ndog_data_long <- dog_data_long %>% \n  mutate(Stage = factor(Stage,\n                        levels = c(\"pre\", \"post\")))\n```\n:::\n\n\n\n:::\n\n### Task 5: Compute descriptives {.unnumbered}\n\nWe want to determine the mean and sd of:\n\n* the pre-scores\n* the post-scores, and\n* the difference scores\n\nStore them in a data object called `descriptives`.\n\n::: {.callout-caution collapse=\"true\" icon=\"false\"}\n\n## Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndescriptives <- dog_lonely %>% \n  summarise(mean_pre = mean(Loneliness_pre),\n            sd_pre = sd(Loneliness_pre),\n            mean_post = mean(Loneliness_post),\n            sd_post = sd(Loneliness_post),\n            diff = mean(Loneliness_diff),\n            sd_diff = sd(Loneliness_diff))\n```\n:::\n\n\n:::\n\n\n### Task 6: Check assumptions {.unnumbered}\n\n\n#### Assumption 1: Continuous DV {.unnumbered} \n\nIs the dependent variable (DV) continuous? Answer: <div class='webex-radiogroup' id='radio_VGULCWOYRZ'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_VGULCWOYRZ\" value=\"x\"></input> <span>No. The DV is the difference in loneliness scores but it is categorical</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_VGULCWOYRZ\" value=\"answer\"></input> <span>Yes. The DV is the difference in loneliness scores and it is continuous</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_VGULCWOYRZ\" value=\"x\"></input> <span>No. The DV is the pre- and post-stages and it is categorical</span></label></div>\n\n\n\n#### Assumption 2: Data are independent {.unnumbered} \n\nEach pair of values in the dataset has to be independent, meaning each pair of values needs to be from a separate participant. Answer: <select class='webex-select'><option value='blank'></option><option value='answer'>yes</option><option value='x'>no</option></select>\n\n#### Assumption 3: Normality {.unnumbered}\n\nLooking at the violin-boxplots below, do you think the assumption of normality holds?\n\n::: {.callout-note}\nThe labels of Plot 2 turned out to be quite long here. I've used the escape character `\\n` here. to break up the title across 2 lines.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Plot 1\nggplot(dog_data_long, aes(x = Stage, y = Loneliness, fill = Stage)) +\n  geom_violin(alpha = 0.5) +\n  geom_boxplot(width = 0.4, alpha = 0.8) +\n  scale_fill_viridis_d(guide = \"none\") +\n  theme_classic() +\n  labs(x = \"Time point\", y = \"mean Loneliness Scores\")\n\n## Plot 2\nggplot(dog_lonely, aes(x = \"\", y = Loneliness_diff)) +\n  geom_violin(fill = \"#21908C\", alpha = 0.5) +\n  geom_boxplot(fill = \"#21908C\", width = 0.4) +\n  theme_classic() +\n  labs(x = \"\",\n       y = \"Difference in mean Loneliness scores \\nbetween pre- and post- intervention\") # \\n forces a manual line break in the axis label\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![Plots displayed to assess normality assumption](08-paired_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\n\n\n\nAnswer:\n\n<div class='webex-radiogroup' id='radio_REMNVPNHPF'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_REMNVPNHPF\" value=\"x\"></input> <span>yes, because both pre- and post-scores in Plot 1 are approximately normally distributed</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_REMNVPNHPF\" value=\"answer\"></input> <span>yes, because the difference scores in Plot 2 are approximately normally distributed</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_REMNVPNHPF\" value=\"x\"></input> <span>no, because both pre- and post-scores in Plot 1 are extremely skewed</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_REMNVPNHPF\" value=\"x\"></input> <span>no, because the difference scores in Plot 2 are extremely skewed</span></label></div>\n\n\n#### Conclusion from assumption tests {.unnumbered}\n\nWith all assumptions tested, which statistical test would you recommend for this analysis?\n\nAnswer: <div class='webex-radiogroup' id='radio_NUGMPJTHQM'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_NUGMPJTHQM\" value=\"answer\"></input> <span>All assumptions held. We will conduct a paired-samples t-test.</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_NUGMPJTHQM\" value=\"x\"></input> <span>The assumption of normality was violated. We will conduct a Wilcoxon signed-rank test.</span></label></div>\n\n\n\n\n### Task 7: Computing a paired-sample t-test with effect size & interpret the output {.unnumbered}\n\n\n* **Step 1**: Compute the paired-sample t-test. The structure of the function is as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(your_data$var1, your_data$var2, paired = TRUE)\n```\n:::\n\n\n\n::: {.callout-caution collapse=\"true\" icon=\"false\"}\n\n## Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(dog_lonely$Loneliness_pre, dog_lonely$Loneliness_post, paired = TRUE)\n```\n:::\n\n\n:::\n\n\n* **Step 2**: Calculate an effect size\n\nCalculate Cohen's D. The structure of the function is as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncohensD(your_data$var1, your_data$var2, method = \"paired\")\n```\n:::\n\n\n\n::: {.callout-caution collapse=\"true\" icon=\"false\"}\n\n## Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncohensD(dog_lonely$Loneliness_pre, dog_lonely$Loneliness_post, method = \"paired\")\n```\n:::\n\n\n:::\n\n\n* **Step 3**: Interpreting the output\n\nBelow are the outputs for the **descriptive statistics** (table), **paired-samples t-test** (main output), and **Cohen’s D** (last line starting with [1]). Based on these, write up the results in APA style and provide an interpretation.\n\n\n::: {.cell}\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| mean_pre|    sd_pre| mean_post|   sd_post|       diff|   sd_diff|\n|--------:|---------:|---------:|---------:|----------:|---------:|\n| 2.040187| 0.5304488|  1.914298| 0.5344914| -0.1258895| 0.2290269|\n\n</div>\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPaired t-test\n\ndata:  dog_lonely$Loneliness_pre and dog_lonely$Loneliness_post\nt = 9.2632, df = 283, p-value < 2.2e-16\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n 0.09913876 0.15264034\nsample estimates:\nmean difference \n      0.1258895 \n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5496716\n```\n:::\n:::\n\n\nWe hypothesised that there would be a significant difference between Loneliness measured before (*M* = <input class='webex-solveme nospaces' size='4' data-answer='[\"2.04\"]'/>, *SD* = <input class='webex-solveme nospaces' size='4' data-answer='[\"0.53\"]'/>) and after (*M* = <input class='webex-solveme nospaces' size='4' data-answer='[\"1.91\"]'/>, *SD* = <input class='webex-solveme nospaces' size='4' data-answer='[\"0.53\"]'/>) the dog intervention. On average, participants felt less lonely after the intervention (*M~diff~* = <input class='webex-solveme nospaces' size='4' data-answer='[\"0.13\"]'/>, *SD~diff~* = <input class='webex-solveme nospaces' size='4' data-answer='[\"0.23\"]'/>). \nUsing a paired-samples t-test, the effect was found to be <select class='webex-select'><option value='blank'></option><option value='answer'>significant</option><option value='x'>non-significant</option></select> and of a <select class='webex-select'><option value='blank'></option><option value='answer'>small</option><option value='x'>medium</option><option value='x'>large</option></select> magnitude, *t*(<input class='webex-solveme nospaces' size='3' data-answer='[\"283\"]'/>) = <input class='webex-solveme nospaces' size='4' data-answer='[\"9.26\"]'/>, *p* <input class='webex-solveme nospaces' size='6' data-answer='[\"< .001\"]'/>, *d* = <input class='webex-solveme nospaces' size='4' data-answer='[\"0.55\"]'/>. We therefore <select class='webex-select'><option value='blank'></option><option value='x'>fail to reject the null hypothesis</option><option value='answer'>reject the null hypothesis in favour of H1</option></select>.\n\n\n## [Test your knowledge]{style=\"color: #F39C12; text-transform: uppercase;\"} {.unnumbered}\n\n#### Question 1 {.unnumbered}\n\n**What is the main purpose of an paired-samples t-test?**\n\n<div class='webex-radiogroup' id='radio_DHZGFJUFNF'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_DHZGFJUFNF\" value=\"x\"></input> <span>To compare means between two independent groups</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_DHZGFJUFNF\" value=\"x\"></input> <span>To test for differences in variances between two independent groups</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_DHZGFJUFNF\" value=\"answer\"></input> <span>To compare means between two related groups</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_DHZGFJUFNF\" value=\"x\"></input> <span>To assess the correlation between two continuous variables</span></label></div>\n\n\n::: {.callout-caution collapse=\"true\" icon=\"false\"}\n\n## Explain this answer\n\nThe paired t-test is used when comparing means from related groups. It requires two measurements from the same group or individual. Examples could be before-and-after measurements (e.g., pre- and post-intervention),\nor repeated measures (e.g., exercise under 2 different conditions, such as indoor and outdoor), etc.\n\n\n:::\n\n#### Question 2 {.unnumbered}\n\n**Which of the following is a key assumption of the paired t-test?**\n\n<div class='webex-radiogroup' id='radio_LQHXETDMRQ'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_LQHXETDMRQ\" value=\"x\"></input> <span>The two samples are independent.</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_LQHXETDMRQ\" value=\"answer\"></input> <span>The differences between paired observations are normally distributed.</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_LQHXETDMRQ\" value=\"x\"></input> <span>The two groups have equal variances.</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_LQHXETDMRQ\" value=\"x\"></input> <span>The dependent variable is categorical.</span></label></div>\n\n\n::: {.callout-caution collapse=\"true\" icon=\"false\"}\n\n## Explain this answer\n\nThe paired t-test assumes that the differences between the paired observations are normally distributed, as the test is applied to these differences, not the raw scores.\n\n:::\n\n\n#### Question 3 {.unnumbered}\n\n**What is the null hypothesis for a paired t-test?**\n\n<div class='webex-radiogroup' id='radio_DHZOXNBZEY'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_DHZOXNBZEY\" value=\"answer\"></input> <span>The differences between paired observations are equal to zero.</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_DHZOXNBZEY\" value=\"x\"></input> <span>There is no relationship between two variables.</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_DHZOXNBZEY\" value=\"x\"></input> <span>The variances of the two samples are equal.</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_DHZOXNBZEY\" value=\"x\"></input> <span>The means of two independent groups are equal.</span></label></div>\n\n\n::: {.callout-caution collapse=\"true\" icon=\"false\"}\n\n## Explain this answer\n\nThe paired t-test specifically tests whether the mean difference between paired observations (e.g., pre-test and post-test scores) is zero, indicating no systematic difference.\n\nWhy the other options are incorrect:\n\n* **The means of two independent groups are equal**: This describes the null hypothesis for an independent t-test, not a paired t-test. The paired t-test is used for related groups or repeated measures, not independent groups.\n* **The variances of the two samples are equal**: This is an assumption that applies to the independent t-test, which compares two unrelated groups. The paired t-test does not test variances; it focuses on the differences between paired observations.\n* **There is no relationship between two variables**: This is not the null hypothesis for a paired t-test. It relates more to correlation or regression analyses, which assess relationships between variables, not mean differences.\n\n:::\n\n\n\n#### Question 4 {.unnumbered}\n\n**A paired-samples t-test was conducted to compare sleep quality scores with (*M* = 7.5, *SD* = 1.8) and without (*M* = 6.0, *SD* = 1.9) white noise, *t*(29) = 4.55, *p* < .001, *d* = 0.82. Answer the questions below.**\n\n* How many participants were included in the study? <input class='webex-solveme nospaces' size='2' data-answer='[\"30\"]'/>\n* What is the effect size, and how would you describe its magnitude?\n  The effect size is <input class='webex-solveme nospaces' size='4' data-answer='[\"0.82\"]'/> and of <select class='webex-select'><option value='blank'></option><option value='x'>small</option><option value='x'>medium</option><option value='answer'>large</option></select> magnitude.\n* Is the result statistically significant? <select class='webex-select'><option value='blank'></option><option value='answer'>The result is statistically significant because p < .001</option><option value='x'>The result is statistically non-significant because p < .001</option></select>\n* Based on the means and standard deviations, how would you summarise the direction of the effect?\n<div class='webex-radiogroup' id='radio_ZZKWSBGIAA'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_ZZKWSBGIAA\" value=\"answer\"></input> <span>Sleep quality was higher with white noise than without white noise.</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_ZZKWSBGIAA\" value=\"x\"></input> <span>Sleep quality was higher without white noise than with white noise.</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_ZZKWSBGIAA\" value=\"x\"></input> <span>Sleep quality was the same in both conditions.</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_ZZKWSBGIAA\" value=\"x\"></input> <span>The direction of the effect cannot be determined from the output.</span></label></div>\n\n\n::: {.callout-caution collapse=\"true\" icon=\"false\"}\n\n## Explain these answers\n\nThe degrees of freedom for a paired-samples t-test are calculated as N - 1 for the number of paired observations. With df = 29, the sample size is 30 participants.\n\nAn effect size of *d* = 0.82 is considered large. This suggests a meaningful and substantial difference in sleep quality between the two conditions.\n\nThe result is statistically significant. The p-value (*p* < .001) indicates that the observed difference in the sample is very unlikely to occur if we assume there is no true difference in the population.\n\nThe mean sleep quality score with white noise (*M* = 7.5) is higher than without white noise (*M* = 6.0), indicating improved sleep quality with white noise.\n\n:::\n",
    "supporting": [
      "08-paired_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}