<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Data skills book for Level 2 Psychology students at the School of Psychology and Neuroscience at the University of Glasgow">

<title>6&nbsp; Chi-square and one-sample t-test – Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./07-independent.html" rel="next">
<link href="./05-dataviz2.html" rel="prev">
<link href="./images/logos/logo_analysis.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
<link rel="stylesheet" href="include/booktem.css">
<link rel="stylesheet" href="include/webex.css">
<link rel="stylesheet" href="include/glossary.css">
<link rel="stylesheet" href="include/style.css">
<link rel="stylesheet" href="include/custom.scss">
<link rel="stylesheet" href="include/styles.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01-basics.html">INDIVIDUAL WALKTHROUGH CHAPTERS</a></li><li class="breadcrumb-item"><a href="./06-chi-square-one-sample.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Chi-square and one-sample t-test</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Analysis</a> 
        <div class="sidebar-tools-main">
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">INDIVIDUAL WALKTHROUGH CHAPTERS</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Projects and R Markdown</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-wrangling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data wrangling I</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-wrangling2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data wrangling II</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-dataviz.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data viz I</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-dataviz2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data viz II</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-chi-square-one-sample.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Chi-square and one-sample t-test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-independent.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Two-sample t-test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-paired.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Paired t-test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Correlations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Simple regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-multiple-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Multiple regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-one-way-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">One-way ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-factorial-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Factorial ANOVA</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">IN-LAB: PAIR-CODING</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pc-A01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2A Lab 1 Week 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pc-A02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2A Lab 2 Week 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pc-A03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2A Lab 3 Week 4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pc-A04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2A Lab 4 Week 5</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pc-A05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2A Lab 5 Week 7</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pc-A06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2A Lab 7 Week 9</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pc-A07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2A Lab 8 Week 10</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pc-B01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2B Lab 1 Week 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pc-B02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2B Lab 2 Week 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pc-B03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2B Lab 3 Week 4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pc-B04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2B Lab 4 Week 5</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pc-B05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2B Lab 5 Week 7</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pc-B06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2B Lab 7 Week 9</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-a-installing-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Installing R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-b-updating-packages.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Updating R, RStudio, and packages</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-d-symbols.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Symbols</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-x-How-to-cite-R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Citing R and RStudio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-y-license.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">License</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar"><div class="quarto-margin-header"><div class="margin-header-item">
<div class="brand-banner">
  <a class="no-external-icon" href="https://psyteachr.github.io/" target="_blank" rel="noopener">
    <img class="nolightbox" src="images/logos/PsyTeachR_books.png" alt="PsyTeachR Books">
    </a>
    </div>
</div></div>
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#intended-learning-outcomes" id="toc-intended-learning-outcomes" class="nav-link active" data-scroll-target="#intended-learning-outcomes">Intended Learning Outcomes</a></li>
  <li><a href="#individual-walkthrough" id="toc-individual-walkthrough" class="nav-link" data-scroll-target="#individual-walkthrough"><span style="color: #F39C12; text-transform: uppercase;">Individual Walkthrough</span></a></li>
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#activity-1-setup-download-the-data" id="toc-activity-1-setup-download-the-data" class="nav-link" data-scroll-target="#activity-1-setup-download-the-data"><span class="header-section-number">6.1</span> Activity 1: Setup &amp; download the data</a></li>
  <li><a href="#activity-2-load-in-the-library-read-in-the-data-and-familiarise-yourself-with-the-data" id="toc-activity-2-load-in-the-library-read-in-the-data-and-familiarise-yourself-with-the-data" class="nav-link" data-scroll-target="#activity-2-load-in-the-library-read-in-the-data-and-familiarise-yourself-with-the-data"><span class="header-section-number">6.2</span> Activity 2: Load in the library, read in the data, and familiarise yourself with the data</a></li>
  <li><a href="#activity-3-data-wrangling" id="toc-activity-3-data-wrangling" class="nav-link" data-scroll-target="#activity-3-data-wrangling"><span class="header-section-number">6.3</span> Activity 3: Data wrangling</a></li>
  <li><a href="#sec-chi_square" id="toc-sec-chi_square" class="nav-link" data-scroll-target="#sec-chi_square"><span class="header-section-number">6.4</span> Activity 4: Cross-tabulation Chi-square test</a>
  <ul class="collapse">
  <li><a href="#task-1-preparing-the-dataframe" id="toc-task-1-preparing-the-dataframe" class="nav-link" data-scroll-target="#task-1-preparing-the-dataframe"><span class="header-section-number">6.4.1</span> Task 1: Preparing the dataframe</a></li>
  <li><a href="#task-2-compute-descriptives" id="toc-task-2-compute-descriptives" class="nav-link" data-scroll-target="#task-2-compute-descriptives"><span class="header-section-number">6.4.2</span> Task 2: Compute descriptives</a></li>
  <li><a href="#task-3-check-assumptions" id="toc-task-3-check-assumptions" class="nav-link" data-scroll-target="#task-3-check-assumptions"><span class="header-section-number">6.4.3</span> Task 3: Check assumptions</a></li>
  <li><a href="#task-4-create-an-appropriate-plot" id="toc-task-4-create-an-appropriate-plot" class="nav-link" data-scroll-target="#task-4-create-an-appropriate-plot"><span class="header-section-number">6.4.4</span> Task 4: Create an appropriate plot</a></li>
  <li><a href="#task-5-compute-a-chi-square-test" id="toc-task-5-compute-a-chi-square-test" class="nav-link" data-scroll-target="#task-5-compute-a-chi-square-test"><span class="header-section-number">6.4.5</span> Task 5: Compute a chi-square test</a></li>
  <li><a href="#task-6-sensitivity-power-analysis" id="toc-task-6-sensitivity-power-analysis" class="nav-link" data-scroll-target="#task-6-sensitivity-power-analysis"><span class="header-section-number">6.4.6</span> Task 6: Sensitivity power analysis</a></li>
  <li><a href="#task-7-the-write-up" id="toc-task-7-the-write-up" class="nav-link" data-scroll-target="#task-7-the-write-up"><span class="header-section-number">6.4.7</span> Task 7: The write-up</a></li>
  </ul></li>
  <li><a href="#sec-onesample" id="toc-sec-onesample" class="nav-link" data-scroll-target="#sec-onesample"><span class="header-section-number">6.5</span> Activity 5: One-sample t-test</a>
  <ul class="collapse">
  <li><a href="#task-1-preparing-the-dataframe-1" id="toc-task-1-preparing-the-dataframe-1" class="nav-link" data-scroll-target="#task-1-preparing-the-dataframe-1"><span class="header-section-number">6.5.1</span> Task 1: Preparing the dataframe</a></li>
  <li><a href="#task-2-compute-descriptives-1" id="toc-task-2-compute-descriptives-1" class="nav-link" data-scroll-target="#task-2-compute-descriptives-1"><span class="header-section-number">6.5.2</span> Task 2: Compute descriptives</a></li>
  <li><a href="#task-3-create-an-appropriate-plot" id="toc-task-3-create-an-appropriate-plot" class="nav-link" data-scroll-target="#task-3-create-an-appropriate-plot"><span class="header-section-number">6.5.3</span> Task 3: Create an appropriate plot</a></li>
  <li><a href="#task-4-check-assumptions" id="toc-task-4-check-assumptions" class="nav-link" data-scroll-target="#task-4-check-assumptions"><span class="header-section-number">6.5.4</span> Task 4: Check assumptions</a></li>
  <li><a href="#task-5-compute-a-one-sample-t-test-and-effect-size" id="toc-task-5-compute-a-one-sample-t-test-and-effect-size" class="nav-link" data-scroll-target="#task-5-compute-a-one-sample-t-test-and-effect-size"><span class="header-section-number">6.5.5</span> Task 5: Compute a One-sample t-test and effect size</a></li>
  <li><a href="#task-6-sensitivity-power-analysis-1" id="toc-task-6-sensitivity-power-analysis-1" class="nav-link" data-scroll-target="#task-6-sensitivity-power-analysis-1"><span class="header-section-number">6.5.6</span> Task 6: Sensitivity power analysis</a></li>
  <li><a href="#task-7-the-write-up-1" id="toc-task-7-the-write-up-1" class="nav-link" data-scroll-target="#task-7-the-write-up-1"><span class="header-section-number">6.5.7</span> Task 7: The write-up</a></li>
  </ul></li>
  <li><a href="#sec-alternative_one_sample" id="toc-sec-alternative_one_sample" class="nav-link" data-scroll-target="#sec-alternative_one_sample"><span class="header-section-number">6.6</span> Activity 6: Non-parametric alternative</a></li>
  <li><a href="#test-your-knowledge" id="toc-test-your-knowledge" class="nav-link" data-scroll-target="#test-your-knowledge"><span style="color: #F39C12; text-transform: uppercase;">Test your knowledge</span></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01-basics.html">INDIVIDUAL WALKTHROUGH CHAPTERS</a></li><li class="breadcrumb-item"><a href="./06-chi-square-one-sample.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Chi-square and one-sample t-test</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-nhstI" class="quarto-section-identifier"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Chi-square and one-sample t-test</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="intended-learning-outcomes" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="intended-learning-outcomes">Intended Learning Outcomes</h2>
<p>By the end of this chapter you should be able to:</p>
<ul>
<li>compute a Cross-tabulation Chi-square test and report the results</li>
<li>compute a one-sample t-test and report the results</li>
<li>understand when to use a non-parametric equivalent for the one-sample t-test, compute it, and report the results</li>
</ul>
</section>
<section id="individual-walkthrough" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="individual-walkthrough"><span style="color: #F39C12; text-transform: uppercase;">Individual Walkthrough</span></h2>
</section>
<section id="overview" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="overview">Overview</h2>
<p>From here on, we will explore inferential statistics, including chi-square test, various t-tests, correlations, ANOVAs, and regression. Most of these tests belong to the General Linear Model (GLM) family, which helps us analyse relationships between variables using linear equations. The chi-square test, while not part of the GLM, is also included here as it’s useful for analysing categorical data.</p>
<p>To help you choose the most appropriate test, refer to the simplified flowchart below. It guides you based on the types of variables - whether they are categorical or continuous.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/Flowchart_tests_drawio.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Simplified flowchart to help select the most appropriate test (created with drawio). View larger version"><img src="images/Flowchart_tests_drawio.png" class="img-fluid figure-img" alt="Simplified flowchart to help select the most appropriate test (created with drawio). View larger version"></a></p>
<figcaption>Simplified flowchart to help select the most appropriate test (created with <a href="https://draw.io/" target="_blank">drawio</a>). <a href="images/Flowchart_tests_drawio.png" target="_blank">View larger version</a></figcaption>
</figure>
</div>
<p>Each test is discussed in its respective chapter with guidance on when and how to apply it:</p>
<ul>
<li>Cross-tabulation chi-Square test (this chapter, <a href="#sec-chi_square" class="quarto-xref"><span>Section 6.4</span></a>)</li>
<li>One-sample t-test (this chapter, <a href="#sec-onesample" class="quarto-xref"><span>Section 6.5</span></a>)</li>
<li>Two-sample or independent t-test (between-subjects design, <a href="07-independent.html" class="quarto-xref"><span>Chapter 7</span></a>)</li>
<li>Paired t-test (within-subjects design, <a href="08-paired.html" class="quarto-xref"><span>Chapter 8</span></a>)</li>
<li>Correlation (<a href="09-correlation.html" class="quarto-xref"><span>Chapter 9</span></a>)</li>
<li>Simple regression (<a href="10-regression.html" class="quarto-xref"><span>Chapter 10</span></a>)</li>
<li>Multiple regression (<a href="11-multiple-regression.html" class="quarto-xref"><span>Chapter 11</span></a>)</li>
<li>One-way ANOVA (<a href="12-one-way-anova.html" class="quarto-xref"><span>Chapter 12</span></a>)</li>
<li>Factorial ANOVA (<a href="13-factorial-anova.html" class="quarto-xref"><span>Chapter 13</span></a>)</li>
</ul>
</section>
<section id="activity-1-setup-download-the-data" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="activity-1-setup-download-the-data"><span class="header-section-number">6.1</span> Activity 1: Setup &amp; download the data</h2>
<p>This week, we will be working with a new dataset. Follow the steps below to set up your project:</p>
<ul>
<li><strong>Create a new project</strong> and name it something meaningful (e.g., “2A_chapter6”, or “06_chi_square_one_sample_t”). See <a href="01-basics.html#sec-project" class="quarto-xref"><span>Section 1.2</span></a> if you need some guidance.</li>
<li><strong>Create a new <code>.Rmd</code> file</strong> and save it to your project folder. See <a href="01-basics.html#sec-rmd" class="quarto-xref"><span>Section 1.3</span></a> if you get stuck.</li>
<li>Delete everything after the setup code chunk (e.g., line 12 and below)</li>
<li><strong>Download the new dataset</strong> here: <a href="data/data_ch6.zip" title="download">data_ch6.zip</a>. This zip file contains one csv file with demographic information and questionnaire data as well as and Excel codebook.</li>
<li>Extract the data files from the zip folder and place them directly in your project folder (next to the project icon, not in a subfolder). For more help, see <a href="01-basics.html#sec-download_data_ch1" class="quarto-xref"><span>Section 1.4</span></a>.</li>
</ul>
<p><strong>Citation</strong></p>
<blockquote class="blockquote">
<p>Ballou, N., Vuorre, M., Hakman, T., Magnusson, K., &amp; Przybylski, A. K. (2024, July 12). Perceived value of video games, but not hours played, predicts mental well-being in adult Nintendo players. <a href="https://doi.org/10.31234/osf.io/3srcw" target="_blank">https://doi.org/10.31234/osf.io/3srcw</a></p>
</blockquote>
<p>As you can see, the study is a pre-print published on PsyArXiv Preprints. The data and supplementary materials are available on OSF: <a href="https://osf.io/6xkdg/" target="_blank">https://osf.io/6xkdg/</a></p>
<p><strong>Abstract</strong></p>
<blockquote class="blockquote">
<p>Studies on video games and well-being often rely on self-report measures or data from a single game. Here, we study how 703 US adults’ time spent playing for over 140,000 hours across 150 Nintendo Switch games relates to their life satisfaction, affect, depressive symptoms, and general mental well-being. We replicate previous findings that playtime over the past two weeks does not predict well-being, and extend these findings to a wider range of timescales (one hour to one year). Results suggest that relationships, if present, dissipate within two hours of gameplay. Our non-causal findings suggest substantial confounding would be needed to shift a meaningful true effect to the observed null. Although playtime was not related to well-being, players’ assessments of the value of game time—so called gaming life fit—was. Results emphasise the importance of defining the gaming population of interest, collecting data from more than one game, and focusing on how players integrate gaming into their lives rather than the amount of time spent.</p>
</blockquote>
<p><strong>Changes made to the dataset</strong></p>
<ul>
<li>We extracted key demographic variables from the rich dataset, including age, gender, ethnicity, employment, education level, and scores from the Warwick-Edinburgh Mental Wellbeing Scale.</li>
<li>We removed rows with missing values and categorical groupings with low observed frequencies for the purpose of this chapter.</li>
<li>We won’t explore any associations related to gaming, but feel free to download the full dataset if you wish to investigate further.</li>
<li>Unlike the original study, which applied strict inclusion criteria, we used more flexible criteria, resulting in a larger sample size than the original analysis.</li>
</ul>
</section>
<section id="activity-2-load-in-the-library-read-in-the-data-and-familiarise-yourself-with-the-data" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="activity-2-load-in-the-library-read-in-the-data-and-familiarise-yourself-with-the-data"><span class="header-section-number">6.2</span> Activity 2: Load in the library, read in the data, and familiarise yourself with the data</h2>
<p>Today, we will be using the following packages: <code>tidyverse</code>, <code>lsr</code>, <code>scales</code>, <code>qqplotr</code>, <code>car</code>, <code>pwr</code>, and <code>rcompanion</code>. If you need to install any of them, do so via the console (see <a href="01-basics.html#sec-install_packages" class="quarto-xref"><span>Section 1.5.1</span></a> for more detail).</p>
<p>Additionally, we will need to read in the data <code>data_ballou_reduced</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="co"># load in the packages</span></span>
<span id="cb1-2"><a href="#cb1-2"></a>???</span>
<span id="cb1-3"><a href="#cb1-3"></a></span>
<span id="cb1-4"><a href="#cb1-4"></a><span class="co"># read in the data</span></span>
<span id="cb1-5"><a href="#cb1-5"></a>data_ballou <span class="ot">&lt;-</span> ???</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="co"># load in the packages</span></span>
<span id="cb2-2"><a href="#cb2-2"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-3"><a href="#cb2-3"></a><span class="fu">library</span>(lsr)</span>
<span id="cb2-4"><a href="#cb2-4"></a><span class="fu">library</span>(scales)</span>
<span id="cb2-5"><a href="#cb2-5"></a><span class="fu">library</span>(qqplotr)</span>
<span id="cb2-6"><a href="#cb2-6"></a><span class="fu">library</span>(car)</span>
<span id="cb2-7"><a href="#cb2-7"></a><span class="fu">library</span>(pwr)</span>
<span id="cb2-8"><a href="#cb2-8"></a><span class="fu">library</span>(rcompanion)</span>
<span id="cb2-9"><a href="#cb2-9"></a></span>
<span id="cb2-10"><a href="#cb2-10"></a><span class="co"># read in the data</span></span>
<span id="cb2-11"><a href="#cb2-11"></a>data_ballou <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data_ballou_reduced.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section>
<section id="activity-3-data-wrangling" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="activity-3-data-wrangling"><span class="header-section-number">6.3</span> Activity 3: Data wrangling</h2>
<p>The categorical variables in our dataset look tidy, but we need to make a few adjustments to prepare for our analysis:</p>
<ul>
<li><strong>Convert <code>gender</code> and <code>education_level</code> into factors</strong> in the original <code>data_ballou</code> object. Our statistical tests require these variables to be factors, and converting them will also help with sorting categories effectively for plotting. Feel free to arrange the categories in a meaningful order.</li>
<li>Create a new data object called <code>data_wemwbs</code> to <strong>calculate the total score for the Warwick-Edinburgh Mental Wellbeing Scale (WEMWBS</strong>): According to the <a href="https://warwick.ac.uk/fac/sci/med/research/platform/wemwbs/using/howto/" target="_blank">official WEMWBS website</a>, the individual item scores should be summed to get the total.</li>
<li><strong>Join</strong> the the original <code>data_ballou</code> dataset with the new <code>data_wemwbs</code> dataset to have all the information in one place.</li>
</ul>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hints
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>We converted categorical variables into factors previously in <a href="04-dataviz.html" class="quarto-xref"><span>Chapter 4</span></a> - refer back if you need a refresher</li>
<li>Check how we handled the <code>QRPs</code> questionnaire in <a href="02-wrangling.html" class="quarto-xref"><span>Chapter 2</span></a> for guidance on aggregating scores</li>
</ul>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a>data_wemwbs <span class="ot">&lt;-</span> data_ballou <span class="sc">%&gt;%</span> </span>
<span id="cb3-2"><a href="#cb3-2"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> wemwbs_1<span class="sc">:</span>wemwbs_14, <span class="at">names_to =</span> <span class="st">"Questions"</span>, <span class="at">values_to =</span> <span class="st">"Scores"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb3-3"><a href="#cb3-3"></a>  <span class="fu">group_by</span>(pid) <span class="sc">%&gt;%</span> </span>
<span id="cb3-4"><a href="#cb3-4"></a>  <span class="fu">summarise</span>(<span class="at">wemwbs_sum =</span> <span class="fu">sum</span>(Scores))</span>
<span id="cb3-5"><a href="#cb3-5"></a></span>
<span id="cb3-6"><a href="#cb3-6"></a>data_ballou <span class="ot">&lt;-</span> data_ballou <span class="sc">%&gt;%</span> </span>
<span id="cb3-7"><a href="#cb3-7"></a>  <span class="fu">mutate</span>(<span class="at">gender =</span> <span class="fu">factor</span>(gender,</span>
<span id="cb3-8"><a href="#cb3-8"></a>                         <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Woman"</span>, <span class="st">"Man"</span>, <span class="st">"Non-binary"</span>)),</span>
<span id="cb3-9"><a href="#cb3-9"></a>         <span class="at">eduLevel =</span> <span class="fu">factor</span>(eduLevel,</span>
<span id="cb3-10"><a href="#cb3-10"></a>                           <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Completed Secondary School"</span>, <span class="st">"Some University but no degree"</span>, <span class="st">"University Bachelors Degree"</span>, <span class="st">"Vocational or Similar"</span>, <span class="st">"Graduate or professional degree (MA, MS, MBA, PhD, etc)"</span>))) <span class="sc">%&gt;%</span> </span>
<span id="cb3-11"><a href="#cb3-11"></a>  <span class="fu">left_join</span>(data_wemwbs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Joining with `by = join_by(pid)`</code></pre>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="sec-chi_square" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="sec-chi_square"><span class="header-section-number">6.4</span> Activity 4: Cross-tabulation Chi-square test</h2>
<p>A Cross-Tabulation Chi-Square Test, also known as a Chi-Square Test of Association or Independence, tests how one variable is associated with the distribution of outcomes in another variable.</p>
<p>We will be performing a Chi-Square test using the categorical variables <strong>gender</strong> and <strong>eduLevel</strong>:</p>
<ul>
<li><strong>Potential research question</strong>: “Is there an association between gender and level of education in the population?”</li>
<li><strong>Null Hypothesis (H<sub>0</sub>)</strong>: “Gender and level of education are independent; there is no association between gender and level of education.”</li>
<li><strong>Alternative Hypothesis (H<sub>1</sub>)</strong>: “Gender and level of education are not independent; there is an association between gender and level of education.”</li>
</ul>
<section id="task-1-preparing-the-dataframe" class="level3" data-number="6.4.1">
<h3 data-number="6.4.1" class="anchored" data-anchor-id="task-1-preparing-the-dataframe"><span class="header-section-number">6.4.1</span> Task 1: Preparing the dataframe</h3>
<p>First, select your variables of interest - here participant id, gender, and education levels. This dataset does not contain missing values, but in future datasets that might, use <code>drop_na()</code> to remove them before converting categorical variables into factors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a>chi_square <span class="ot">&lt;-</span> data_ballou <span class="sc">%&gt;%</span> </span>
<span id="cb5-2"><a href="#cb5-2"></a>  <span class="fu">select</span>(pid, gender, eduLevel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="task-2-compute-descriptives" class="level3" data-number="6.4.2">
<h3 data-number="6.4.2" class="anchored" data-anchor-id="task-2-compute-descriptives"><span class="header-section-number">6.4.2</span> Task 2: Compute descriptives</h3>
<p>Next, we need to calculate counts for each combination of the variables, which is best done in a frequency table - or more precisely a <strong>contingency table</strong> since we are looking at a combination of 2 categorical variables (sometimes they are called crosstabulation and two-way tables).</p>
<p>This will also allow us to verify that there are no missing values in any cells, as the function we’re using cannot handle missing values</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a>chi_square_frequency <span class="ot">&lt;-</span> chi_square <span class="sc">%&gt;%</span> </span>
<span id="cb6-2"><a href="#cb6-2"></a>  <span class="fu">count</span>(gender, eduLevel) <span class="sc">%&gt;%</span> </span>
<span id="cb6-3"><a href="#cb6-3"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> eduLevel, <span class="at">values_from =</span> n)</span>
<span id="cb6-4"><a href="#cb6-4"></a></span>
<span id="cb6-5"><a href="#cb6-5"></a>chi_square_frequency</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 6%">
<col style="width: 15%">
<col style="width: 17%">
<col style="width: 16%">
<col style="width: 12%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">gender</th>
<th style="text-align: right;">Completed Secondary School</th>
<th style="text-align: right;">Some University but no degree</th>
<th style="text-align: right;">University Bachelors Degree</th>
<th style="text-align: right;">Vocational or Similar</th>
<th style="text-align: right;">Graduate or professional degree (MA, MS, MBA, PhD, etc)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Woman</td>
<td style="text-align: right;">63</td>
<td style="text-align: right;">118</td>
<td style="text-align: right;">169</td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">65</td>
</tr>
<tr class="even">
<td style="text-align: left;">Man</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">125</td>
<td style="text-align: right;">250</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">81</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Non-binary</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">10</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>We should be fine here, even though the count for the non-binary/vocational category is quite low.</p>
</section>
<section id="task-3-check-assumptions" class="level3" data-number="6.4.3">
<h3 data-number="6.4.3" class="anchored" data-anchor-id="task-3-check-assumptions"><span class="header-section-number">6.4.3</span> Task 3: Check assumptions</h3>
<section id="assumption-1-categorical-data" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="assumption-1-categorical-data">Assumption 1: Categorical data</h4>
<p>Both variables should be categorical, measured at either the ordinal or nominal level.</p>
<p>We can confirm that for our dataset. Gender is <select class="webex-select"><option value="blank"></option><option value="x">ordinal</option><option value="answer">nominal</option></select>, and level of education is <select class="webex-select"><option value="blank"></option><option value="answer">ordinal</option><option value="x">nominal</option></select>.</p>
</section>
<section id="assumption-2-independent-observartions" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="assumption-2-independent-observartions">Assumption 2: Independent observartions</h4>
<p>Each observation in the dataset has to be independent, meaning the value of one observation does not affect the value of any other.</p>
<p>And we assume as much for our data.</p>
</section>
<section id="assumption-3-cells-in-the-contingency-table-are-mutually-exclusive" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="assumption-3-cells-in-the-contingency-table-are-mutually-exclusive">Assumption 3: Cells in the contingency table are mutually exclusive</h4>
<p>Each individual can belong to only one cell in the contingency table. We can confirm this by examining the data and reviewing the contingency table.</p>
</section>
<section id="assumption-4-expected-frequencies-are-sufficiently-large" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="assumption-4-expected-frequencies-are-sufficiently-large">Assumption 4: Expected frequencies are sufficiently large</h4>
<p>Assumption 4 is not an assumption that is listed consistently across various sources. When it is, it suggests that expected frequencies are larger than 5 or at least 80% of the the expected frequencies are above 5 and none of them are below 1. However, Danielle Navarro points out that this seems to be a “somewhat conservative” criterion and should be taken as “rough guidelines” only (see <a href="https://learningstatisticswithr.com/book/chisquare.html#chisqassumptions" target="_blank">https://learningstatisticswithr.com/book/chisquare.html#chisqassumptions</a>.</p>
<p>This is information, we can either compute manually (see lecture slides) or wait till we get the output from the inferential statistics later.</p>
</section>
</section>
<section id="task-4-create-an-appropriate-plot" class="level3" data-number="6.4.4">
<h3 data-number="6.4.4" class="anchored" data-anchor-id="task-4-create-an-appropriate-plot"><span class="header-section-number">6.4.4</span> Task 4: Create an appropriate plot</h3>
<p>Now we can create the appropriate plot. Which plot would you choose when building one from object <code>chi_square</code>? A <select class="webex-select"><option value="blank"></option><option value="answer">Barchart</option><option value="x">Histogram</option><option value="x">Scatterplot</option><option value="x">Violin-Boxplot</option></select> with geom layer <select class="webex-select"><option value="blank"></option><option value="x">geom_col</option><option value="answer">geom_bar</option><option value="x">geom_histogram</option><option value="x">geom_point</option><option value="x">geom_boxplot and geom_violin</option></select></p>
<p>Try creating the plot on your own before checking the solution. Feel free to practice adding different layers to make the plot pretty!</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
One possible solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>… is a grouped bar chart.</p>
<p>I played about with the labels of the x-axis categories since the graduate label is super long. Google was my friend in this instance and showed me a nifty function called <code>label_wrap()</code> from the <code>scales</code> package which automatically inserts line breaks after a set number of characters. Setting it to 12 characters looked best. (See other options for long labels at <a href="https://www.andrewheiss.com/blog/2022/06/23/long-labels-ggplot/" target="_blank">https://www.andrewheiss.com/blog/2022/06/23/long-labels-ggplot/</a>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="fu">ggplot</span>(chi_square, <span class="fu">aes</span>(<span class="at">x =</span> eduLevel, <span class="at">fill =</span> gender)) <span class="sc">+</span></span>
<span id="cb7-2"><a href="#cb7-2"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span> </span>
<span id="cb7-3"><a href="#cb7-3"></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">name =</span> <span class="st">"Gender"</span>) <span class="sc">+</span></span>
<span id="cb7-4"><a href="#cb7-4"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">name =</span> <span class="st">"Level of Education"</span>,</span>
<span id="cb7-5"><a href="#cb7-5"></a>                   <span class="at">labels =</span> <span class="fu">label_wrap</span>(<span class="dv">12</span>)) <span class="sc">+</span></span>
<span id="cb7-6"><a href="#cb7-6"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">name =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb7-7"><a href="#cb7-7"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="06-chi-square-one-sample_files/figure-html/unnamed-chunk-8-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2"><img src="06-chi-square-one-sample_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="task-5-compute-a-chi-square-test" class="level3" data-number="6.4.5">
<h3 data-number="6.4.5" class="anchored" data-anchor-id="task-5-compute-a-chi-square-test"><span class="header-section-number">6.4.5</span> Task 5: Compute a chi-square test</h3>
<p>Before we can do that, we need to turn our tibble into a dataframe - the <code>associationTest()</code> function we are using to compute the Chi-square test does not like tibbles. [<em>you have nooooo clue how long that took to figure out - let’s say the error message was not exactly helpful</em>]</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a>chi_square_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(chi_square)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we can run the <code>associationTest()</code> function from the <code>lsr</code> package. The first argument is a formula. It starts with a <code>~</code> followed by the two variables you want to associate, separated by a <code>+</code>. The second argument is the dataframe.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a><span class="fu">associationTest</span>(<span class="at">formula =</span> <span class="sc">~</span> eduLevel <span class="sc">+</span> gender, <span class="at">data =</span> chi_square_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in associationTest(formula = ~eduLevel + gender, data = chi_square_df):
Expected frequencies too small: chi-squared approximation may be incorrect</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Chi-square test of categorical association

Variables:   eduLevel, gender 

Hypotheses: 
   null:        variables are independent of one another
   alternative: some contingency exists between variables

Observed contingency table:
                                                         gender
eduLevel                                                  Woman Man Non-binary
  Completed Secondary School                                 63  70          9
  Some University but no degree                             118 125         23
  University Bachelors Degree                               169 250         20
  Vocational or Similar                                      42  34          4
  Graduate or professional degree (MA, MS, MBA, PhD, etc)    65  81         10

Expected contingency table under the null hypothesis:
                                                         gender
eduLevel                                                  Woman   Man
  Completed Secondary School                               59.9  73.4
  Some University but no degree                           112.2 137.5
  University Bachelors Degree                             185.2 227.0
  Vocational or Similar                                    33.8  41.4
  Graduate or professional degree (MA, MS, MBA, PhD, etc)  65.8  80.7
                                                         gender
eduLevel                                                  Non-binary
  Completed Secondary School                                    8.65
  Some University but no degree                                16.21
  University Bachelors Degree                                  26.75
  Vocational or Similar                                         4.88
  Graduate or professional degree (MA, MS, MBA, PhD, etc)       9.51

Test results: 
   X-squared statistic:  13.594 
   degrees of freedom:  8 
   p-value:  0.093 

Other information: 
   estimated effect size (Cramer's v):  0.079 
   warning: expected frequencies too small, results may be inaccurate</code></pre>
</div>
</div>
<p>The output is quite informative as it gives information about:</p>
<ul>
<li>the variables that were tested,</li>
<li>the null and alternative hypotheses,</li>
<li>a table with the observed frequencies (which matches our calculations in <code>chi_square_frequency</code> without the rows/columns of the missing values we removed),</li>
<li>an output of the frequencies you’d expect if the null hypothesis were true,</li>
<li>the result of the hypothesis test, and</li>
<li>the effect size Cramer’s v.</li>
</ul>
<p>It also gives us a <strong>warning message</strong> saying that expected frequencies are too small and that the chi-squared approximation may be incorrect. This relates to Assumption 4. Depending on your stance on Assumption 4, you may choose to either address or ignore this warning.</p>
<p>The p-value indicates that we do not reject the null hypothesis, as it is greater than 0.05.</p>
</section>
<section id="task-6-sensitivity-power-analysis" class="level3" data-number="6.4.6">
<h3 data-number="6.4.6" class="anchored" data-anchor-id="task-6-sensitivity-power-analysis"><span class="header-section-number">6.4.6</span> Task 6: Sensitivity power analysis</h3>
<p>A <strong>sensitivity power analysis allows you to determine the minimum effect size that the study could reliably detect</strong> given the number of participants you have in the sample (i.e., sample size), the alpha level at 0.05, and an assumed power of 0.8. Remember, power analysis relies on four key factors — alpha, power, effect size, and sample size (APES). If you know three of these, you can calculate the fourth.</p>
<p>For a Chi-square test, we use the <code>pwr.chisq.test()</code> function from the <code>pwr</code> package. In this case, we already know the alpha, power, and sample size, and we want to calculate the smallest effect size detectable with this design. The function also requires the degrees of freedom (<code>df</code>), which tells <code>R</code> how many groups are being compared. You can find the <code>df</code> value in the output of your Chi-square test (e.g., from <code>associationTest()</code>).</p>
<p>The key arguments for this function are:</p>
<ul>
<li><code>w</code> = Effect size (Cohen’s omega, ⍵). <em>(Leave this one out to calculate it.)</em></li>
<li><code>N</code> = Total number of observations.</li>
<li><code>df</code> = Degree of freedom (from your Chi-square test).</li>
<li><code>sig.level</code> = The significance level of the study (usually set to 0.05).</li>
<li><code>power</code> = The power level of the study (usually set to 0.8).</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a><span class="fu">pwr.chisq.test</span>(<span class="at">N =</span> <span class="dv">1083</span>,</span>
<span id="cb12-2"><a href="#cb12-2"></a>               <span class="at">df =</span> <span class="dv">8</span>,</span>
<span id="cb12-3"><a href="#cb12-3"></a>               <span class="at">sig.level =</span> <span class="fl">0.05</span>,</span>
<span id="cb12-4"><a href="#cb12-4"></a>               <span class="at">power =</span> <span class="fl">0.8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Chi squared power calculation 

              w = 0.1178008
              N = 1083
             df = 8
      sig.level = 0.05
          power = 0.8

NOTE: N is the number of observations</code></pre>
</div>
</div>
<p>This output gives us the smallest effect size detectable with this design. To interpret it, we need to compare it with the effect size from our test output. However, there’s a catch: the power analysis reports Cohen’s omega (⍵), while the Chi-square test reports Cramer’s V. To make them comparable, we need to convert Cramer’s V into Cohen’s omega.</p>
<p>The formula to do so is:</p>
<p><span class="math display">\[
Cohen's \; \omega = Cramer's \; V * \sqrt(k-1)
\]</span></p>
<p>where <code>k</code> s the number of categories in the variable with fewer levels.</p>
<p>For example, if one variable has 3 levels (e.g., <code>gender</code>) and the other has 5 (e.g., <code>eduLevel</code>), then <code>k = 3</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a>w <span class="ot">=</span> <span class="fl">0.079</span> <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="dv">3-1</span>)</span>
<span id="cb14-2"><a href="#cb14-2"></a></span>
<span id="cb14-3"><a href="#cb14-3"></a>w</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1117229</code></pre>
</div>
</div>
<p><strong>Comparison:</strong></p>
<p>With 1,083 observations, alpha = 0.05, and power = 0.8, the smallest detectable effect size is `⍵ = 0.118. Our calculated effect size from the Chi-square test was ⍵ = 0.112. Because 0.112 is smaller than 0.118, our study is slightly underpowered, meaning there’s a higher risk of missing an effect that actually exists (a Type II error). In this case, because our Chi-square test was non-significant, the lack of significance might reflect low power rather than the true absence of an effect.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>If one of your categorical variables only has 2 levels (e.g., yes/no), then Cramer’s V and Cohen’s ⍵ are identical. In that case, you can compare them directly:</p>
<ul>
<li>if Cohen’s ⍵ (sensitivity) &lt; Cramer’s V (observed), your design is sufficiently powered.</li>
<li>if Cramer’s V (observed) &lt; Cohen’s ⍵ (sensitivity), your study is underpowered, and you should be cautious about drawing strong conclusions.</li>
</ul>
</div>
</div>
</section>
<section id="task-7-the-write-up" class="level3" data-number="6.4.7">
<h3 data-number="6.4.7" class="anchored" data-anchor-id="task-7-the-write-up"><span class="header-section-number">6.4.7</span> Task 7: The write-up</h3>
<p>The Cross-Tabulation Chi-Square Test revealed a small association between Gender and Level of Education that was not statistically significant, <span class="math inline">\(\chi^2(8) = 13.59, p = .093, V = .079\)</span>. We therefore fail to reject the null hypothesis. However, a sensitivity power analysis indicated that the study was slightly underpowered, which means the non-significant result may reflect limited power rather than the true absence of an association.</p>
</section>
</section>
<section id="sec-onesample" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="sec-onesample"><span class="header-section-number">6.5</span> Activity 5: One-sample t-test</h2>
<p>The one-sample t-test is used to determine whether a sample comes from a population with a specific mean. This population mean is not always known, but is sometimes hypothesised.</p>
<p>We will perform a one-sample t-test using the continuous variable <strong>wemwbs_sum</strong>. The <a href="https://warwick.ac.uk/fac/sci/med/research/platform/wemwbs/using/howto/" target="_blank">official website for the Warwick-Edinburgh Mental Wellbeing Scales</a> states that the “WEMWBS has a mean score of 51.0 in general population samples in the UK with a standard deviation of 7 (Tennant et al., 2007)”.</p>
<ul>
<li><strong>Potential research question</strong>: “Is the average mental well-being of gamers different from the general population’s average well-being?”</li>
<li><strong>Null Hypothesis (H<sub>0</sub>)</strong>: “The summed-up WEMWBS score of gamers is not different to 51.0.”</li>
<li><strong>Alternative Hypothesis (H<sub>1</sub>)</strong>: “The summed-up WEMWBS score of gamers is different from 51.0.”</li>
</ul>
<section id="task-1-preparing-the-dataframe-1" class="level3" data-number="6.5.1">
<h3 data-number="6.5.1" class="anchored" data-anchor-id="task-1-preparing-the-dataframe-1"><span class="header-section-number">6.5.1</span> Task 1: Preparing the dataframe</h3>
<p>First, we need to select the variables of interest: participant ID and <code>wemwbs_sum</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a>one_sample <span class="ot">&lt;-</span> data_ballou <span class="sc">%&gt;%</span> </span>
<span id="cb16-2"><a href="#cb16-2"></a>  <span class="fu">select</span>(pid, wemwbs_sum)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="task-2-compute-descriptives-1" class="level3" data-number="6.5.2">
<h3 data-number="6.5.2" class="anchored" data-anchor-id="task-2-compute-descriptives-1"><span class="header-section-number">6.5.2</span> Task 2: Compute descriptives</h3>
<p>Next, we want to compute means and standard deviations for our variable of interest. This should be straight forward. Try it yourself and then compare your result with the solution below.</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1"></a>descriptives <span class="ot">&lt;-</span> one_sample <span class="sc">%&gt;%</span> </span>
<span id="cb17-2"><a href="#cb17-2"></a>  <span class="fu">summarise</span>(<span class="at">mean_wemwbs =</span> <span class="fu">mean</span>(wemwbs_sum),</span>
<span id="cb17-3"><a href="#cb17-3"></a>            <span class="at">sd =</span> <span class="fu">sd</span>(wemwbs_sum))</span>
<span id="cb17-4"><a href="#cb17-4"></a></span>
<span id="cb17-5"><a href="#cb17-5"></a>descriptives</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">mean_wemwbs</th>
<th style="text-align: right;">sd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">45.42013</td>
<td style="text-align: right;">10.88615</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="task-3-create-an-appropriate-plot" class="level3" data-number="6.5.3">
<h3 data-number="6.5.3" class="anchored" data-anchor-id="task-3-create-an-appropriate-plot"><span class="header-section-number">6.5.3</span> Task 3: Create an appropriate plot</h3>
<p>This is the plot you will want to include in your report, so make sure everything is clearly labelled. Which plot would you choose? Try creating one on your own first, then compare it with the solution below.</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a><span class="fu">ggplot</span>(one_sample, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> wemwbs_sum)) <span class="sc">+</span></span>
<span id="cb18-2"><a href="#cb18-2"></a>  <span class="fu">geom_violin</span>(<span class="at">fill =</span> <span class="st">"#FB8D61"</span>, <span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span> <span class="co"># alpha for opacity, fill for adding colour</span></span>
<span id="cb18-3"><a href="#cb18-3"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"#FB8D61"</span>, <span class="at">width =</span> <span class="fl">0.5</span>) <span class="sc">+</span> <span class="co"># change width of the boxes</span></span>
<span id="cb18-4"><a href="#cb18-4"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb18-5"><a href="#cb18-5"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">""</span>,</span>
<span id="cb18-6"><a href="#cb18-6"></a>       <span class="at">y =</span> <span class="st">"Total WEMWBS Scores"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="06-chi-square-one-sample_files/figure-html/unnamed-chunk-15-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3"><img src="06-chi-square-one-sample_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="task-4-check-assumptions" class="level3" data-number="6.5.4">
<h3 data-number="6.5.4" class="anchored" data-anchor-id="task-4-check-assumptions"><span class="header-section-number">6.5.4</span> Task 4: Check assumptions</h3>
<section id="assumption-1-continuous-dv" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="assumption-1-continuous-dv">Assumption 1: Continuous DV</h4>
<p>The dependent variable (DV) needs to be measured at interval or ratio level. We can confirm that by looking at <code>one_sample</code>.</p>
</section>
<section id="assumption-2-data-are-independent" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="assumption-2-data-are-independent">Assumption 2: Data are independent</h4>
<p>There should be no relationship between the observations. While this is an important assumption, it is more related to study design and isn’t something we can easily test for. Anyway, we will assume this assumption holds for our data.</p>
</section>
<section id="assumption-3-no-significant-outliers" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="assumption-3-no-significant-outliers">Assumption 3: No significant outliers</h4>
<p>We can check for that visually, for example in the violin-boxplot above.</p>
<p>It appears there is one outlier in the lower tail. However, upon inspecting the <code>one_sample</code> data, we see it is a single participant with a score of 14, which is a possible value. Additionally, with a large sample size of 1,083 participants, removing a single outlier makes not much sense. Thus, we have checked this assumption, considered this outlier not significant, and therefore keep this observation in the dataset.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you decide to remove any outliers, remember to recalculate the descriptive statistics.</p>
</div>
</div>
</section>
<section id="assumption-4-dv-should-be-approximately-normally-distributed" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="assumption-4-dv-should-be-approximately-normally-distributed">Assumption 4: DV should be approximately normally distributed</h4>
<p>We can already check normality from the violin-boxplot above but you could also use a histogram, a density plot, or a Q-Q plot as an alternative to assess normality visually.</p>
<p>Each of these options shows that <strong>the data is normally distributed</strong>. This allows us to proceed with a parametric test, specifically a one-sample t-test.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Alternatives to visually assess normality
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" aria-current="page">Histogram</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Density plot</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false">Q-Q plot</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<p>We’ve already covered histograms in <a href="05-dataviz2.html" class="quarto-xref"><span>Chapter 5</span></a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1"></a><span class="fu">ggplot</span>(one_sample, <span class="fu">aes</span>(<span class="at">x =</span> wemwbs_sum)) <span class="sc">+</span></span>
<span id="cb19-2"><a href="#cb19-2"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">1</span>, <span class="at">fill =</span> <span class="st">"magenta"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="06-chi-square-one-sample_files/figure-html/unnamed-chunk-16-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4"><img src="06-chi-square-one-sample_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<p>A density plot shows a smooth distribution curve of the data. Unlike a histogram, the height of the curve reflects the proportion of data within each range rather than the frequency of individual values. This means the curve shows where data points are concentrated, not how many times each value appears.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a><span class="fu">ggplot</span>(one_sample, <span class="fu">aes</span>(<span class="at">x =</span> wemwbs_sum)) <span class="sc">+</span></span>
<span id="cb20-2"><a href="#cb20-2"></a>  <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"magenta"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="06-chi-square-one-sample_files/figure-html/unnamed-chunk-17-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5"><img src="06-chi-square-one-sample_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<p>Q-Q plot stands for Quantile-Quantile Plot and compare two distributions by matching a common set of quantiles. Essentially, it compares the distribution of your data to a normal distribution and plots the points along a 45-degree line.</p>
<p><strong>If the dots in the Q-Q plot fall roughly along that line, we can assume the data is normally distributed. If they stray away from the line (and worse in some sort of pattern), we might not assume normality and conduct a non-parametric test instead. For the non-parametric equivalent, see <a href="#sec-alternative_one_sample" class="quarto-xref"><span>Section 6.6</span></a>.</strong></p>
<p>To create the Q-Q plot, you can use either the <code>car</code> or <code>qqplotr</code> package</p>
<ul>
<li>The <code>qqPlot()</code> function is a single line but requires BaseR syntax (i.e., the <code>$</code> symbol) to access the column within the data object. For example, <code>one_sample$wemwbs_sum</code> directs R to look for a column named <code>wemwbs_sum</code> that is located within the data object <code>one_sample</code>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1"></a><span class="co"># Version 1 with the car package</span></span>
<span id="cb21-2"><a href="#cb21-2"></a><span class="fu">qqPlot</span>(one_sample<span class="sc">$</span>wemwbs_sum)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 295 394</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-qqplot1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-qqplot1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="06-chi-square-one-sample_files/figure-html/fig-qqplot1-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Figure&nbsp;6.1: Q-Q plot created with the car package"><img src="06-chi-square-one-sample_files/figure-html/fig-qqplot1-1.png" class="img-fluid figure-img" width="672"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-qqplot1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.1: Q-Q plot created with the car package
</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li>If you have gotten used to ggplot by now, and prefer avoiding BaseR, you can use the package <code>qqplotr</code>. The downside is that you have to add the points, the line, and the confidence envelope yourself. On the plus, it has layers like ggplot, and is more customisable (just in case you wanted to look at something more colourful in the 2 seconds it’ll take you to assess normality).</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1"></a><span class="co"># Version 2 with package qqplotr</span></span>
<span id="cb23-2"><a href="#cb23-2"></a><span class="fu">ggplot</span>(one_sample, <span class="fu">aes</span>(<span class="at">sample =</span> wemwbs_sum)) <span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3"></a>  <span class="fu">stat_qq_band</span>(<span class="at">fill =</span> <span class="st">"#FB8D61"</span>, <span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb23-4"><a href="#cb23-4"></a>  <span class="fu">stat_qq_line</span>(<span class="at">colour =</span> <span class="st">"#FB8D61"</span>) <span class="sc">+</span></span>
<span id="cb23-5"><a href="#cb23-5"></a>  <span class="fu">stat_qq_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-qqplot2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-qqplot2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="06-chi-square-one-sample_files/figure-html/fig-qqplot2-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="Figure&nbsp;6.2: Q-Q plot created with the qqplotr package"><img src="06-chi-square-one-sample_files/figure-html/fig-qqplot2-1.png" class="img-fluid figure-img" width="672"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-qqplot2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.2: Q-Q plot created with the qqplotr package
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<p>You could also assess normality with the <strong>Shapiro-Wilk’s test</strong>. The null hypothesis is that the population is distributed normally. Therefore, if the p-value of the Shapiro-Wilk’s test smaller than .05, normality is rejected.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Shapiro-Wilk is an OK method for small sample sizes (e.g., smaller than 50 samples) if the deviation from normality is fairly obvious. If we are dealing with slight deviations from normality, it might not be sensitive enough to pick that up. But t-tests, ANOVAs etc. should be robust for slight deviations from normality anyway.</p>
<p>In contrast, when you have large sample sizes, Shapiro-Wilk is overly sensitive and will definitely produce a significant p-value regardless of what the distribution looks like. So don’t rely on its output when you have large sample sizes, and be mindful of its output when you have small sample sizes.</p>
</div>
</div>
<p>The function in R for this test is <code>shapiro.test()</code> which is part of BaseR. This means, we need to specify our data object, use the <code>$</code>, and indicate the column we want to address.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a><span class="fu">shapiro.test</span>(one_sample<span class="sc">$</span>wemwbs_sum)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  one_sample$wemwbs_sum
W = 0.99404, p-value = 0.0002619</code></pre>
</div>
</div>
<p>No surprise here! The test shows a p-value of &lt; .001 due to our large sample size of over 1000 participants. Nevertheless, if you decided on using the Shapiro-Wilk test in your report, you’d need to write this result up in APA style: <span class="math inline">\(W = .99, p &lt; .001\)</span>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Report-writing Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Either choose visual or computational inspection for normality tests. NO NEED TO DO BOTH!!!</p>
<ul>
<li>State what method you used and your reasons for choosing the method (visual/computational and what plot/test you used)</li>
<li>State the outcome of the test - for visual inspection just say whether normality assumption held or not (no need to include that extra plot in the results section). For computational methods, report the test result in APA style</li>
<li>State the conclusions you draw from it - parametric or non-parametric test</li>
</ul>
</div>
</div>
</section>
</section>
<section id="task-5-compute-a-one-sample-t-test-and-effect-size" class="level3" data-number="6.5.5">
<h3 data-number="6.5.5" class="anchored" data-anchor-id="task-5-compute-a-one-sample-t-test-and-effect-size"><span class="header-section-number">6.5.5</span> Task 5: Compute a One-sample t-test and effect size</h3>
<p>To compute a one-sample t-test, we can use the <code>t.test() function</code>, which is part of Base R. And yes, you guessed it, our first argument should follow the pattern <code>data$column</code>. The second argument, <code>mu</code>, specifies the population mean we are testing our sample against (in this case, 51.0). The <code>alternative</code> is “two.sided” by default, so it can be omitted if you are conducting a two-sided test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a><span class="fu">t.test</span>(one_sample<span class="sc">$</span>wemwbs_sum, <span class="at">mu =</span> <span class="fl">51.0</span>, <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  one_sample$wemwbs_sum
t = -16.868, df = 1082, p-value &lt; 2.2e-16
alternative hypothesis: true mean is not equal to 51
95 percent confidence interval:
 44.77106 46.06920
sample estimates:
mean of x 
 45.42013 </code></pre>
</div>
</div>
<p>The output is quite informative. It provides information about:</p>
<ul>
<li>the variable column that was tested,</li>
<li>the t value, degrees of freedom, and p,</li>
<li>the alternative hypothesis,</li>
<li>a 95% confidence interval,</li>
<li>and the mean of the column (which matches the one we computed in the descriptive - yay)</li>
</ul>
<p>What it doesn’t give us is an <strong>effect size</strong>. Meh. So we will need to compute one ourselves.</p>
<p>We will calculate <strong>Cohen’s d</strong> using the function <code>cohensD()</code> from the <code>lsr</code> package. Similar to the t-test we just conducted, the first argument is <code>data$column</code>, the second argument is <code>mu</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1"></a><span class="fu">cohensD</span>(one_sample<span class="sc">$</span>wemwbs_sum, <span class="at">mu =</span> <span class="fl">51.0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5125662</code></pre>
</div>
</div>
</section>
<section id="task-6-sensitivity-power-analysis-1" class="level3" data-number="6.5.6">
<h3 data-number="6.5.6" class="anchored" data-anchor-id="task-6-sensitivity-power-analysis-1"><span class="header-section-number">6.5.6</span> Task 6: Sensitivity power analysis</h3>
<p>A <strong>sensitivity power analysis allows you to determine the minimum effect size that the study could reliably detect</strong> given the number of participants you have in the sample (i.e., sample size), the alpha level at 0.05, and an assumed power of 0.8.</p>
<p>To perform this calculation, we use the <code>pwr.t.test()</code> function from the <code>pwr</code> package. This function relies on four key factors — alpha, power, effect size, and sample size (APES). If you know three, you can calculate the fourth. Since we have three specified, we can solve for the effect size. Additionally, we need to specify the <code>type</code> argument to indicate we are using a one-sample t-test, and set <code>alternative</code> to “two.sided” for a non-directional hypothesis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1"></a><span class="fu">pwr.t.test</span>(<span class="at">n =</span> <span class="dv">1083</span>, <span class="at">sig.level =</span> <span class="fl">0.05</span>, <span class="at">power =</span> <span class="fl">0.8</span>, <span class="at">type =</span> <span class="st">"one.sample"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     One-sample t test power calculation 

              n = 1083
              d = 0.08520677
      sig.level = 0.05
          power = 0.8
    alternative = two.sided</code></pre>
</div>
</div>
<p>So the smallest effect size we can detect with a sample size of 1083, an alpha level of 0.05, and power of 0.8 is 0.09. This is a smaller value than the actual effect size we calculated with our CohensD function above (i.e., 0.51) which means our analysis is sufficiently powered.</p>
</section>
<section id="task-7-the-write-up-1" class="level3" data-number="6.5.7">
<h3 data-number="6.5.7" class="anchored" data-anchor-id="task-7-the-write-up-1"><span class="header-section-number">6.5.7</span> Task 7: The write-up</h3>
<p>A one-sample t-test was computed to determine whether the average mental well-being of gamers as measured by the WEMWBS was different to the population well-being mean. The average WEMWBS of the gamers <span class="math inline">\((N = 1083, M = 45.42, SD = 10.89)\)</span> was significantly lower than the population mean well-being score of 51.0, <span class="math inline">\(t(1082) = 16.87, p &lt; .001, d = .51\)</span>. The strength of the effect is considered medium and the study was sufficiently powered. We therefore reject the null hypothesis in favour of H<sub>1</sub>.</p>
</section>
</section>
<section id="sec-alternative_one_sample" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="sec-alternative_one_sample"><span class="header-section-number">6.6</span> Activity 6: Non-parametric alternative</h2>
<p>If any of the assumptions are violated, switch to the non-parametric alternative. For the one-sample t-test, this would be a <strong>One-sample Wilcoxon signed-rank test</strong>. Instead of the mean, it compares the median of a sample against a single value (i.e., the population median).</p>
<p>That means we will need to determine the population median, and calculate some <strong>summary stats</strong> for our sample:</p>
<ul>
<li>The population median is listed in a supporting document on the <a href="https://warwick.ac.uk/fac/sci/med/research/platform/wemwbs/using/howto/" target="_blank">official WEMWBS website</a> as 53.0.</li>
<li>We can easily calculate the summary statistics using the function <code>summary()</code>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1"></a><span class="fu">summary</span>(one_sample)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     pid              wemwbs_sum   
 Length:1083        Min.   :14.00  
 Class :character   1st Qu.:38.00  
 Mode  :character   Median :46.00  
                    Mean   :45.42  
                    3rd Qu.:53.00  
                    Max.   :70.00  </code></pre>
</div>
</div>
<p>The function to <strong>compute a one-sample Wilcoxon test</strong> is <code>wilcox.test()</code> which is part of BaseR. Code-wise, it works very similar to the one-sample t-test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1"></a><span class="fu">wilcox.test</span>(one_sample<span class="sc">$</span>wemwbs_sum, <span class="at">mu =</span> <span class="fl">53.0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon signed rank test with continuity correction

data:  one_sample$wemwbs_sum
V = 87218, p-value &lt; 2.2e-16
alternative hypothesis: true location is not equal to 53</code></pre>
</div>
</div>
<p>As we can see, the output shows a V value, but for the final write-up, we need to report <strong>the standardised test statistic Z</strong> in the final write-up. Unfortunately, this requires manual calculation. According to Andy Field (2012, p.&nbsp;665), we need to use the qnorm function on the halved p-value from our Wilcoxon test above. Here, we store the p-value in the <code>Global Environment</code> as <code>p_wilcoxon</code>. This retains more decimal places than shown in the output, giving us a more precise Z value.”</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1"></a><span class="co"># storing the p-value</span></span>
<span id="cb36-2"><a href="#cb36-2"></a>p_wilcoxon <span class="ot">&lt;-</span> <span class="fu">wilcox.test</span>(one_sample<span class="sc">$</span>wemwbs_sum, <span class="at">mu =</span> <span class="fl">53.0</span>)<span class="sc">$</span>p.value</span>
<span id="cb36-3"><a href="#cb36-3"></a></span>
<span id="cb36-4"><a href="#cb36-4"></a><span class="co"># calculate the z value from half the p-value</span></span>
<span id="cb36-5"><a href="#cb36-5"></a>z <span class="ot">=</span> <span class="fu">qnorm</span>(p_wilcoxon<span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb36-6"><a href="#cb36-6"></a>z</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -19.12264</code></pre>
</div>
</div>
<p>We also need to <strong>calculate the effect size <code>r</code></strong> for the One-sample Wilcoxon signed-rank test. This can be done using the <code>wilcoxonOneSampleR()</code> function from the <code>rcompanion</code> package. By default, the result is rounded to three decimal places, but you can adjust this by adding the <code>digits</code> argument.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1"></a><span class="fu">wilcoxonOneSampleR</span>(one_sample<span class="sc">$</span>wemwbs_sum, <span class="at">mu =</span> <span class="fl">53.0</span>, <span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    r 
-0.59 </code></pre>
</div>
</div>
<p>Now we have all the numbers we need to <strong>write up the results</strong>:</p>
<p>A One-sample Wilcoxon signed-rank test was used to compare Gamers’ mental-wellbeing median scores (Mdn = 46.0) to the population median of 53.0. The test showed a significant difference, <span class="math inline">\(Z = -19.12, p &lt; .001, r = .590\)</span>. The strength of the effect is considered medium. We therefore reject the null hypothesis in favour of H<sub>1</sub>.</p>
</section>
<section id="test-your-knowledge" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="test-your-knowledge"><span style="color: #F39C12; text-transform: uppercase;">Test your knowledge</span></h2>
<section id="question-1-conceptual-understanding---chi-square-test" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-1-conceptual-understanding---chi-square-test">Question 1: Conceptual Understanding - Chi-Square Test</h4>
<p><strong>What is the primary purpose of a Chi-square test?</strong></p>
<div id="radio_JSYKIORSXH" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_JSYKIORSXH" value="x"> <span>To assess the correlation between two continuous variables</span></label><label><input type="radio" autocomplete="off" name="radio_JSYKIORSXH" value="answer"> <span>To test the relationship between categorical variables</span></label><label><input type="radio" autocomplete="off" name="radio_JSYKIORSXH" value="x"> <span>To test for differences in variances</span></label><label><input type="radio" autocomplete="off" name="radio_JSYKIORSXH" value="x"> <span>To compare means between two groups</span></label>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Explain this answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The Chi-square test evaluates whether there is an association or relationship between two categorical variables. Those variables can either be nominal or ordinal.</p>
</div>
</div>
</div>
</section>
<section id="question-2-application---chi-square-test" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-2-application---chi-square-test">Question 2: Application - Chi-Square Test</h4>
<p><strong>Which of the following scenarios would require a Chi-square test?</strong></p>
<div id="radio_CNAUDTGACC" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_CNAUDTGACC" value="x"> <span>Comparing the average exam scores of students in two classrooms</span></label><label><input type="radio" autocomplete="off" name="radio_CNAUDTGACC" value="answer"> <span>Determining if there is an association between people’s favourite pizza topping and their region of residence</span></label><label><input type="radio" autocomplete="off" name="radio_CNAUDTGACC" value="x"> <span>Testing whether the average height of basketball players differs from the general population</span></label><label><input type="radio" autocomplete="off" name="radio_CNAUDTGACC" value="x"> <span>Assessing whether the reaction times of drivers are influenced by caffeine consumption</span></label>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Explain this answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The only option with 2 categorical variables is pizza topping (e.g., pepperoni, vegetarian, cheese) and region of residence (e.g., North, South, East, West).</p>
</div>
</div>
</div>
</section>
<section id="question-3-interpreting-output---chi-square-test" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-3-interpreting-output---chi-square-test">Question 3: Interpreting Output - Chi-Square Test</h4>
<p><strong>In a Chi-square test, the p-value is .005. What does this imply if the significance level is set at .05?</strong></p>
<div id="radio_DPTBYDMTUM" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_DPTBYDMTUM" value="x"> <span>The null hypothesis is not rejected; there is no significant association.</span></label><label><input type="radio" autocomplete="off" name="radio_DPTBYDMTUM" value="x"> <span>The null hypothesis is rejected; there is no significant association.</span></label><label><input type="radio" autocomplete="off" name="radio_DPTBYDMTUM" value="x"> <span>The null hypothesis is not rejected; there is a significant association.</span></label><label><input type="radio" autocomplete="off" name="radio_DPTBYDMTUM" value="answer"> <span>The null hypothesis is rejected; there is a significant association.</span></label>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Explain this answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A p-value of .005 is less than the significance level (.05), indicating that the observed association between the variables is unlikely to have happened by chance.</p>
</div>
</div>
</div>
</section>
<section id="question-4-using-r---chi-square-test" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-4-using-r---chi-square-test">Question 4: Using R - Chi-Square Test</h4>
<p><strong>Which of the following R functions is used to perform a Chi-square test and displays a Cramer’s V in the output?</strong></p>
<div id="radio_VSZXNELBFN" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_VSZXNELBFN" value="x"> <span>t.test()</span></label><label><input type="radio" autocomplete="off" name="radio_VSZXNELBFN" value="x"> <span>chisq.test()</span></label><label><input type="radio" autocomplete="off" name="radio_VSZXNELBFN" value="x"> <span>one.sample()</span></label><label><input type="radio" autocomplete="off" name="radio_VSZXNELBFN" value="answer"> <span>associationTest()</span></label>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Explain this answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The <code>associationTest()</code> function from the <code>lsr</code> package performs a Chi-square test and directly provides Cramer’s V as part of the output. The <code>chisq.test()</code> function exists it but does not compute Cramer’s V. The other options either don’t exist or don’t meet the criteria.</p>
</div>
</div>
</div>
</section>
<section id="question-5-conceptual-understanding---one-sample-t-test" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-5-conceptual-understanding---one-sample-t-test">Question 5: Conceptual Understanding - One-sample t-test</h4>
<p><strong>What is the null hypothesis in a one-sample t-test?</strong></p>
<div id="radio_GDYILEKRBG" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_GDYILEKRBG" value="x"> <span>The sample mean is greater than the population mean</span></label><label><input type="radio" autocomplete="off" name="radio_GDYILEKRBG" value="answer"> <span>The sample mean is equal to the population mean</span></label><label><input type="radio" autocomplete="off" name="radio_GDYILEKRBG" value="x"> <span>The population mean is equal to zero</span></label><label><input type="radio" autocomplete="off" name="radio_GDYILEKRBG" value="x"> <span>The sample mean is less than the population mean</span></label>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Explain this answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The one-sample t-test tests whether the sample mean is significantly different from a known or hypothesised population mean.</p>
</div>
</div>
</div>
</section>
<section id="question-6-application---one-sample-t-test" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-6-application---one-sample-t-test">Question 6: Application - One-sample t-test</h4>
<p><strong>Which of the following scenarios would require a one-sample t-test?</strong></p>
<div id="radio_NUREVDSGUM" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_NUREVDSGUM" value="x"> <span>Comparing the average exam scores of students in two classrooms</span></label><label><input type="radio" autocomplete="off" name="radio_NUREVDSGUM" value="x"> <span>Determining if there is an association between people’s favourite pizza topping and their region of residence</span></label><label><input type="radio" autocomplete="off" name="radio_NUREVDSGUM" value="answer"> <span>Testing whether the average height of basketball players differs from the general population</span></label><label><input type="radio" autocomplete="off" name="radio_NUREVDSGUM" value="x"> <span>Assessing whether the reaction times of drivers are influenced by caffeine consumption</span></label>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Explain this answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A one-sample t-test is appropriate when comparing the mean of a single sample (e.g., basketball players’ heights) to a known or hypothesised population mean (e.g., mean of the general population). The other options involve comparisons between groups (option 1), categorical associations (option 2), or repeated measures (option 4).</p>
</div>
</div>
</div>
</section>
<section id="question-7-interpreting-output---one-sample-t-test" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-7-interpreting-output---one-sample-t-test">Question 7: Interpreting Output - One-sample t-test</h4>
<p><strong>If the p-value in a one-sample t-test is .15 and the significance level is .05, what is the conclusion?</strong></p>
<div id="radio_QHECDKENUL" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_QHECDKENUL" value="x"> <span>The sample mean is significantly different from the population mean.</span></label><label><input type="radio" autocomplete="off" name="radio_QHECDKENUL" value="x"> <span>The sample mean is equal to the population mean.</span></label><label><input type="radio" autocomplete="off" name="radio_QHECDKENUL" value="x"> <span>The sample mean is further from the population mean than expected by chance.</span></label><label><input type="radio" autocomplete="off" name="radio_QHECDKENUL" value="answer"> <span>The sample mean is not significantly different from the population mean.</span></label>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Explain this answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Since the p-value (.15) is greater than the significance level (.05), we fail to reject the null hypothesis. This means there is no evidence to suggest that the sample mean is significantly different from the population mean.</p>
<p>However, this does not mean we have evidence to confirm that the sample mean is exactly equal to the population mean. In statistics, ‘not significantly different’ is not the same as ‘equal.’ Therefore, the option ‘The sample mean is equal to the population mean’ is incorrect.</p>
</div>
</div>
</div>
</section>
<section id="question-8-using-r---one-sample-t-test" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-8-using-r---one-sample-t-test">Question 8: Using R - One-sample t-test</h4>
<p><strong>Which of the following R functions is used to perform a one-sample t-test?</strong></p>
<div id="radio_WYBGWSRKJB" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_WYBGWSRKJB" value="x"> <span>one.sample()</span></label><label><input type="radio" autocomplete="off" name="radio_WYBGWSRKJB" value="x"> <span>associationTest()</span></label><label><input type="radio" autocomplete="off" name="radio_WYBGWSRKJB" value="x"> <span>chisq.test()</span></label><label><input type="radio" autocomplete="off" name="radio_WYBGWSRKJB" value="answer"> <span>t.test()</span></label>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Explain this answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><code>t.test()</code> is the standard function in R for performing a one-sample t-test. In the next 2 weeks, we will see that the function can also be used for two-sample and paired t-tests.</p>
<p>The function <code>one.sample()</code> does not exist.</p>
<p>The other two functions perform Chi-square tests, which are specifically designed for categorical variables. They cannot be used when one of the variables is continuous.</p>
</div>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script>



/* update total correct if #webex-total_correct exists */

update_total_correct = function() {

  console.log("webex: update total_correct");



  var t = document.getElementsByClassName("webex-total_correct");

  for (var i = 0; i < t.length; i++) {

    p = t[i].parentElement;

    var correct = p.getElementsByClassName("webex-correct").length;

    var solvemes = p.getElementsByClassName("webex-solveme").length;

    var radiogroups = p.getElementsByClassName("webex-radiogroup").length;

    var selects = p.getElementsByClassName("webex-select").length;



    t[i].innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";

  }

}



/* webex-solution button toggling function */

b_func = function() {

  console.log("webex: toggle hide");



  var cl = this.parentElement.classList;

  if (cl.contains('open')) {

    cl.remove("open");

  } else {

    cl.add("open");

  }

}



/* check answers */

check_func = function() {

  console.log("webex: check answers");



  var cl = this.parentElement.classList;

  if (cl.contains('unchecked')) {

    cl.remove("unchecked");

    this.innerHTML = "Hide Answers";

  } else {

    cl.add("unchecked");

    this.innerHTML = "Show Answers";

  }

}



/* function for checking solveme answers */

solveme_func = function(e) {

  console.log("webex: check solveme");



  var real_answers = JSON.parse(this.dataset.answer);

  var my_answer = this.value;

  var cl = this.classList;

  if (cl.contains("ignorecase")) {

    my_answer = my_answer.toLowerCase();

  }

  if (cl.contains("nospaces")) {

    my_answer = my_answer.replace(/ /g, "")

  }



  if (my_answer == "") {

    cl.remove("webex-correct");

    cl.remove("webex-incorrect");

  } else if (real_answers.includes(my_answer)) {

    cl.add("webex-correct");

    cl.remove("webex-incorrect");

  } else {

    cl.add("webex-incorrect");

    cl.remove("webex-correct");

  }



  // match numeric answers within a specified tolerance

  if(this.dataset.tol > 0){

    var tol = JSON.parse(this.dataset.tol);

    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)

    if (matches.reduce((a, b) => a + b, 0) > 0) {

      cl.add("webex-correct");

    } else {

      cl.remove("webex-correct");

    }

  }



  // added regex bit

  if (cl.contains("regex")){

    answer_regex = RegExp(real_answers.join("|"))

    if (answer_regex.test(my_answer)) {

      cl.add("webex-correct");

    }

  }



  update_total_correct();

}



/* function for checking select answers */

select_func = function(e) {

  console.log("webex: check select");



  var cl = this.classList



  /* add style */

  cl.remove("webex-incorrect");

  cl.remove("webex-correct");

  if (this.value == "answer") {

    cl.add("webex-correct");

  } else if (this.value != "blank") {

    cl.add("webex-incorrect");

  }



  update_total_correct();

}



/* function for checking radiogroups answers */

radiogroups_func = function(e) {

  console.log("webex: check radiogroups");



  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');

  var cl = checked_button.parentElement.classList;

  var labels = checked_button.parentElement.parentElement.children;



  /* get rid of styles */

  for (i = 0; i < labels.length; i++) {

    labels[i].classList.remove("webex-incorrect");

    labels[i].classList.remove("webex-correct");

  }



  /* add style */

  if (checked_button.value == "answer") {

    cl.add("webex-correct");

  } else {

    cl.add("webex-incorrect");

  }



  update_total_correct();

}



window.onload = function() {

  console.log("webex onload");

  /* set up solution buttons */

  var buttons = document.getElementsByTagName("button");



  for (var i = 0; i < buttons.length; i++) {

    if (buttons[i].parentElement.classList.contains('webex-solution')) {

      buttons[i].onclick = b_func;

    }

  }



  var check_sections = document.getElementsByClassName("webex-check");

  console.log("check:", check_sections.length);

  for (var i = 0; i < check_sections.length; i++) {

    check_sections[i].classList.add("unchecked");



    let btn = document.createElement("button");

    btn.innerHTML = "Show Answers";

    btn.classList.add("webex-check-button");

    btn.onclick = check_func;

    check_sections[i].appendChild(btn);



    let spn = document.createElement("span");

    spn.classList.add("webex-total_correct");

    check_sections[i].appendChild(spn);

  }



  /* set up webex-solveme inputs */

  var solveme = document.getElementsByClassName("webex-solveme");



  for (var i = 0; i < solveme.length; i++) {

    /* make sure input boxes don't auto-anything */

    solveme[i].setAttribute("autocomplete","off");

    solveme[i].setAttribute("autocorrect", "off");

    solveme[i].setAttribute("autocapitalize", "off");

    solveme[i].setAttribute("spellcheck", "false");

    solveme[i].value = "";



    /* adjust answer for ignorecase or nospaces */

    var cl = solveme[i].classList;

    var real_answer = solveme[i].dataset.answer;

    if (cl.contains("ignorecase")) {

      real_answer = real_answer.toLowerCase();

    }

    if (cl.contains("nospaces")) {

      real_answer = real_answer.replace(/ /g, "");

    }

    solveme[i].dataset.answer = real_answer;



    /* attach checking function */

    solveme[i].onkeyup = solveme_func;

    solveme[i].onchange = solveme_func;



    solveme[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")

  }



  /* set up radiogroups */

  var radiogroups = document.getElementsByClassName("webex-radiogroup");

  for (var i = 0; i < radiogroups.length; i++) {

    radiogroups[i].onchange = radiogroups_func;

  }



  /* set up selects */

  var selects = document.getElementsByClassName("webex-select");

  for (var i = 0; i < selects.length; i++) {

    selects[i].onchange = select_func;

    selects[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")

  }



  update_total_correct();

}



</script>

<script>

// open rdrr links externally ----



var exlinks = document.querySelectorAll("a[href^='https://rdrr.io']");

var exlink_func = function(){

  window.open(this.href);

  return false;

};

for (var i = 0; i < exlinks.length; i++) {

    exlinks[i].addEventListener('click', exlink_func, false);

}



// visible second sidebar in mobile ----



function move_sidebar() {

  var toc = document.getElementById("TOC");

  var small_sidebar = document.querySelector("#quarto-sidebar .sidebar-menu-container");

  var right_sidebar = document.getElementById("quarto-margin-sidebar");



  if (window.innerWidth < 768) {

    small_sidebar.append(toc);

  } else {

    right_sidebar.append(toc);

  }

}

move_sidebar();

window.onresize = move_sidebar;

</script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./05-dataviz2.html" class="pagination-link" aria-label="Data viz II">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data viz II</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./07-independent.html" class="pagination-link" aria-label="Two-sample t-test">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Two-sample t-test</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>CC-BY (2025) Gaby Mahrholz Carolina E. Kuepper-Tetzel</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","selector":".lightbox","openEffect":"zoom","loop":false,"descPosition":"bottom"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>