<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="description" content="Data skills book for Level 2 Psychology students at the School of Psychology and Neuroscience at the University of Glasgow">
<title>Analysis - 9&nbsp; Correlations</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./10-regression.html" rel="next">
<link href="./08-paired.html" rel="prev">
<link href="./images/logos/logo_analysis.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
<link rel="stylesheet" href="include/booktem.css">
<link rel="stylesheet" href="include/webex.css">
<link rel="stylesheet" href="include/glossary.css">
<link rel="stylesheet" href="include/style.css">
<link rel="stylesheet" href="include/custom.scss">
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01-basics.html">INDIVIDUAL WALKTHROUGH CHAPTERS</a></li><li class="breadcrumb-item"><a href="./09-correlation.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Correlations</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Analysis</a> 
        <div class="sidebar-tools-main">
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
<li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
</div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">INDIVIDUAL WALKTHROUGH CHAPTERS</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Projects and R Markdown</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-wrangling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data wrangling I</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-wrangling2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data wrangling II</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-dataviz.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data viz I</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-dataviz2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data viz II</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-chi-square-one-sample.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Chi-square and one-sample t-test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-independent.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Two-sample t-test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-paired.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Paired t-test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-correlation.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Correlations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Simple regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-multiple-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Multiple regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-one-way-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">One-way ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-factorial-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Factorial ANOVA</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">IN-LAB: PAIR-CODING</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pc-A01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2A Lab 1 Week 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pc-A02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2A Lab 2 Week 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pc-A03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2A Lab 3 Week 4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pc-A04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2A Lab 4 Week 5</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pc-A05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2A Lab 5 Week 7</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pc-A06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2A Lab 7 Week 9</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pc-A07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2A Lab 8 Week 10</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pc-B01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2B Lab 1 Week 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pc-B02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2B Lab 2 Week 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pc-B03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2B Lab 3 Week 4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pc-B04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2B Lab 4 Week 5</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pc-B05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2B Lab 5 Week 7</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pc-B06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2B Lab 7 Week 9</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-a-installing-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Installing R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-b-updating-packages.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Updating R, RStudio, and packages</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-d-symbols.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Symbols</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-x-How-to-cite-R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Citing R and RStudio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-y-license.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">License</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#intended-learning-outcomes" id="toc-intended-learning-outcomes" class="nav-link active" data-scroll-target="#intended-learning-outcomes">Intended Learning Outcomes</a></li>
  <li><a href="#individual-walkthrough" id="toc-individual-walkthrough" class="nav-link" data-scroll-target="#individual-walkthrough"><span style="color: #F39C12; text-transform: uppercase;">Individual Walkthrough</span></a></li>
  <li><a href="#activity-1-setup-download-the-data" id="toc-activity-1-setup-download-the-data" class="nav-link" data-scroll-target="#activity-1-setup-download-the-data"><span class="header-section-number">9.1</span> Activity 1: Setup &amp; download the data</a></li>
  <li><a href="#activity-2-library-and-data-for-today" id="toc-activity-2-library-and-data-for-today" class="nav-link" data-scroll-target="#activity-2-library-and-data-for-today"><span class="header-section-number">9.2</span> Activity 2: Library and data for today</a></li>
  <li><a href="#activity-3-familiarise-yourself-with-the-data" id="toc-activity-3-familiarise-yourself-with-the-data" class="nav-link" data-scroll-target="#activity-3-familiarise-yourself-with-the-data"><span class="header-section-number">9.3</span> Activity 3: Familiarise yourself with the data</a></li>
  <li><a href="#activity-4-preparing-the-dataframe" id="toc-activity-4-preparing-the-dataframe" class="nav-link" data-scroll-target="#activity-4-preparing-the-dataframe"><span class="header-section-number">9.4</span> Activity 4: Preparing the dataframe</a></li>
  <li><a href="#activity-5-compute-descriptives" id="toc-activity-5-compute-descriptives" class="nav-link" data-scroll-target="#activity-5-compute-descriptives"><span class="header-section-number">9.5</span> Activity 5: Compute descriptives</a></li>
  <li><a href="#activity-6-create-an-appropriate-plot" id="toc-activity-6-create-an-appropriate-plot" class="nav-link" data-scroll-target="#activity-6-create-an-appropriate-plot"><span class="header-section-number">9.6</span> Activity 6: Create an appropriate plot</a></li>
  <li><a href="#activity-7-check-assumptions" id="toc-activity-7-check-assumptions" class="nav-link" data-scroll-target="#activity-7-check-assumptions"><span class="header-section-number">9.7</span> Activity 7: Check assumptions</a></li>
  <li><a href="#activity-8-pearsons-correlation-effect-size" id="toc-activity-8-pearsons-correlation-effect-size" class="nav-link" data-scroll-target="#activity-8-pearsons-correlation-effect-size"><span class="header-section-number">9.8</span> Activity 8: Pearson’s correlation &amp; effect size</a></li>
  <li><a href="#activity-9-sensitivity-power-analysis" id="toc-activity-9-sensitivity-power-analysis" class="nav-link" data-scroll-target="#activity-9-sensitivity-power-analysis"><span class="header-section-number">9.9</span> Activity 9: Sensitivity power analysis</a></li>
  <li><a href="#activity-10-the-write-up" id="toc-activity-10-the-write-up" class="nav-link" data-scroll-target="#activity-10-the-write-up"><span class="header-section-number">9.10</span> Activity 10: The write-up</a></li>
  <li><a href="#activity-11-non-parametric-alternative" id="toc-activity-11-non-parametric-alternative" class="nav-link" data-scroll-target="#activity-11-non-parametric-alternative"><span class="header-section-number">9.11</span> Activity 11: Non-parametric alternative</a></li>
  <li><a href="#test-your-knowledge" id="toc-test-your-knowledge" class="nav-link" data-scroll-target="#test-your-knowledge"><span style="color: #F39C12; text-transform: uppercase;">Test your knowledge</span></a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-cor" class="quarto-section-identifier"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Correlations</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><section id="intended-learning-outcomes" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="intended-learning-outcomes">Intended Learning Outcomes</h2>
<p>By the end of this chapter you should be able to:</p>
<ul>
<li>Compute a Pearson correlation and effectively report the results.</li>
<li>Understand when to use a non-parametric equivalent of correlation, compute it, and report the results.</li>
</ul></section><section id="individual-walkthrough" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="individual-walkthrough"><span style="color: #F39C12; text-transform: uppercase;">Individual Walkthrough</span></h2>
</section><section id="activity-1-setup-download-the-data" class="level2" data-number="9.1"><h2 data-number="9.1" class="anchored" data-anchor-id="activity-1-setup-download-the-data">
<span class="header-section-number">9.1</span> Activity 1: Setup &amp; download the data</h2>
<p>This week, we will be working with a new dataset. Follow the steps below to set up your project:</p>
<ul>
<li>
<strong>Create a new project</strong> and name it something meaningful (e.g., “2A_chapter9”, or “09_correlation”). See <a href="01-basics.html#sec-project"><span>Section&nbsp;1.2</span></a> if you need some guidance.</li>
<li>
<strong>Create a new <code>.Rmd</code> file</strong> and save it to your project folder. See <a href="01-basics.html#sec-rmd"><span>Section&nbsp;1.3</span></a> if you need help.</li>
<li>Delete everything after the setup code chunk (e.g., line 12 and below)</li>
<li>
<strong>Download the new dataset</strong> here: <a href="data/data_ch9.zip" title="download">data_ch9.zip</a>. The zip folder includes the following files:
<ul>
<li>
<code>Soupbowl_data_dictionary.xlsx</code>: A codebook with detailed variable descriptions</li>
<li>
<code>data_ch9_correlation.csv</code>: A CSV file containing data from the experiment and demographic information</li>
<li>A copy of the paper by Lopez et al.&nbsp;(2024) and the Supplementary materials</li>
</ul>
</li>
<li>Extract the data files from the zip folder and place them in your project folder. If you need help, see <a href="01-basics.html#sec-download_data_ch1"><span>Section&nbsp;1.4</span></a>.</li>
</ul>
<p><strong>Citation</strong></p>
<blockquote class="blockquote">
<p>Lopez, A., Choi, A. K., Dellawar, N. C., Cullen, B. C., Avila Contreras, S., Rosenfeld, D. L., &amp; Tomiyama, A. J. (2024). Visual cues and food intake: A preregistered replication of Wansink et al.&nbsp;(2005). <em>Journal of Experimental Psychology: General, 153</em>(2), 275–281. <a href="https://doi.org/10.1037/xge0001503" target="_blank">https://doi.org/10.1037/xge0001503</a></p>
</blockquote>
<p>The preregistration, data and supplementary materials are available on OSF &amp; APA’s “Journal of Experimental Psychology: General”:</p>
<ul>
<li>Pre-reg: <a href="https://osf.io/ux42g" target="_blank">https://osf.io/ux42g</a>
</li>
<li>Data: <a href="https://osf.io/8q647/" target="_blank">https://osf.io/8q647/</a>
</li>
<li>SupMats: <a href="https://supp.apa.org/psycarticles/supplemental/xge0001503/xge0001503.pdf" target="_blank">https://supp.apa.org/psycarticles/supplemental/xge0001503/xge0001503.pdf</a>
</li>
</ul>
<p><strong>Abstract</strong></p>
<blockquote class="blockquote">
<p>Imagine a bowl of soup that never emptied, no matter how many spoonfuls you ate—when and how would you know to stop eating? Satiation can play a role in regulating eating behavior, but research suggests visual cues may be just as important. In a seminal study by <a href="https://doi.org/10.1038/oby.2005.12" target="_blank">Wansink et al.&nbsp;(2005)</a>, researchers used self-refilling bowls to assess how visual cues of portion size would influence intake. The study found that participants who unknowingly ate from self-refilling bowls ate more soup than did participants eating from normal (not self-refilling) bowls. Despite consuming 73% more soup, however, participants in the self-refilling condition did not believe they had consumed more soup, nor did they perceive themselves as more satiated than did participants eating from normal bowls. Given recent concerns regarding the validity of research from the Wansink lab, we conducted a preregistered direct replication study of Wansink et al.&nbsp;(2005) with a more highly powered sample (N =464 vs.&nbsp;54 in the original study). We found that most results replicated, albeit with half the effect size (d= 0.45 instead of 0.84), with participants in the self-refilling bowl condition eating significantly more soup than those in the control condition. Like the original study, participants in the selfrefilling condition did not believe they had consumed any more soup than participants in the control condition. These results suggest that eating can be strongly controlled by visual cues, which can even override satiation.</p>
</blockquote>
<p><strong>Public Significance Statement</strong></p>
<blockquote class="blockquote">
<p>Results from this study are relevant to public health and science given the influence that the bottomless soup bowls study had on public policy and the skepticism surrounding research from the Wansink lab. We found that what the eyes see plays a significant role in how much people eat and how full they feel. Given the high prevalence of diseases of overconsumption, this study has implications for the regulation of eating behavior.</p>
</blockquote>
<p><strong>Changes made to the dataset</strong></p>
<ul>
<li>The basis for <code>data_ch9_correlation.csv</code> is the file named <code>included&amp;excludedFINAL.sav</code> on OSF. It contains 632 observations.</li>
<li>The original authors used an SPSS file format, which was exported as a csv.</li>
<li>The original authors coded missing values as 999 and 888. These were replaced with actual missing values (NA).</li>
<li>Variables <code>M_postsoup</code> and <code>Condition</code> were removed so we can practice more data wrangling. It also gives us an opportunity to include one of Gaby’s favourite functions <code>coalesce()</code>.</li>
<li>No other changes were made.</li>
</ul></section><section id="activity-2-library-and-data-for-today" class="level2" data-number="9.2"><h2 data-number="9.2" class="anchored" data-anchor-id="activity-2-library-and-data-for-today">
<span class="header-section-number">9.2</span> Activity 2: Library and data for today</h2>
<p>Today, we will use the following packages: <code>tidyverse</code>, <code>ggExtra</code>, <code>correlation</code>, <code>qqplotr</code>, and <code>pwr</code>. As always, you may need to install any packages you have not used/ installed before (see <a href="01-basics.html#sec-install_packages"><span>Section&nbsp;1.5.1</span></a> if you need some help).</p>
<p>Additionally, we will read in today’s data from <code>data_ch9_correlation</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="co"># load in the packages</span></span>
<span id="cb1-2"><a href="#cb1-2"></a>???</span>
<span id="cb1-3"><a href="#cb1-3"></a></span>
<span id="cb1-4"><a href="#cb1-4"></a><span class="co"># read in the data</span></span>
<span id="cb1-5"><a href="#cb1-5"></a>lopez_data <span class="ot">&lt;-</span> ???</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="co"># load in the packages</span></span>
<span id="cb2-2"><a href="#cb2-2"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-3"><a href="#cb2-3"></a><span class="fu">library</span>(ggExtra)</span>
<span id="cb2-4"><a href="#cb2-4"></a><span class="fu">library</span>(correlation)</span>
<span id="cb2-5"><a href="#cb2-5"></a><span class="fu">library</span>(qqplotr)</span>
<span id="cb2-6"><a href="#cb2-6"></a><span class="fu">library</span>(pwr)</span>
<span id="cb2-7"><a href="#cb2-7"></a></span>
<span id="cb2-8"><a href="#cb2-8"></a><span class="co"># read in the data</span></span>
<span id="cb2-9"><a href="#cb2-9"></a>lopez_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data_ch9_correlation.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section><section id="activity-3-familiarise-yourself-with-the-data" class="level2" data-number="9.3"><h2 data-number="9.3" class="anchored" data-anchor-id="activity-3-familiarise-yourself-with-the-data">
<span class="header-section-number">9.3</span> Activity 3: Familiarise yourself with the data</h2>
<p>As usual, take some time to familiarise yourself with the data before starting the analysis. Review the codebook to understand the variables and their measurement.</p>
<p>We notice that <code>lopez_data</code> contains data from 632 participants, whereas the Lopez et al.&nbsp;(2024) paper reports a total of 654 participants. Have a look at the data and the paper. Can you explain the discrepancy?</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Explanation
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Lopez et al.&nbsp;appear to have published data for both the participants included in the final sample (464 participants) and those excluded after discovering the true purpose of the study (168 participants). However, an additional 22 participants were excluded due to experimenter error, and their data were not recorded.</p>
</div>
</div>
</div>
<p>Today, we will focus on a few correlation values and attempt to reproduce some of the results presented in Table 2 of Lopez et al.&nbsp;(2024).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/lopez_table2.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Table 2 (Lopez et al., 2024)</figcaption></figure>
</div>
<p>As shown in the table above, the original authors aimed to replicate the correlations reported by Wansink et al.&nbsp;(2005). Specifically, they examined the following relationships:</p>
<ul>
<li>Estimated ounces of soup consumed with actual consumption volume</li>
<li>Estimated calories of soup consumed with actual consumption volume</li>
</ul>
<p>These correlations were calculated for three groups: participants who ate from normal bowls, participants who ate from self-refilling bowls, and the combined group of all participants.</p>
</section><section id="activity-4-preparing-the-dataframe" class="level2" data-number="9.4"><h2 data-number="9.4" class="anchored" data-anchor-id="activity-4-preparing-the-dataframe">
<span class="header-section-number">9.4</span> Activity 4: Preparing the dataframe</h2>
<p>To calculate correlations, the data must be in wide format. Fortunately, <code>lopez_data</code> is already in wide format. However, if your data is organised differently, ensure that each variable is in its own column.</p>
<section id="step-1-excluding-participants-data" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="step-1-excluding-participants-data">Step 1: Excluding participants’ data</h4>
<p>Check that only participants who meet the recruitment criteria are included, and exclude those who do not. Lopez and colleagues made this straightforward by including the variable <code>Included</code> in the dataset. This variable indicates which participants were included in the final dataset (value of 1) and which were excluded (value of 0). After completing this step, our new data object should contain 464 participants.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Your Turn
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Create a new data object named <code>lopez_included</code> that contains only the participants marked as included in the final dataset (i.e., those with a value of 1 in the <code>Included</code> variable).</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a>lopez_included <span class="ot">&lt;-</span> lopez_data <span class="sc">%&gt;%</span> </span>
<span id="cb3-2"><a href="#cb3-2"></a>  <span class="fu">filter</span>(Included <span class="sc">==</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</section><section id="step-2-selecting-relevant-variables" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="step-2-selecting-relevant-variables">Step 2: Selecting relevant variables</h4>
<p>Big datasets can be messy, so it is often helpful to focus only on the variables relevant to your analysis. For this task, we want to include the following variables:</p>
<ul>
<li><code>ParticipantID</code></li>
<li>Estimated ounces of food consumed (<code>OzEstimate</code>)</li>
<li>Estimated calories of food consumed (<code>CalEstimate</code>)</li>
<li>Consumption volume - Experimental soup intake (<code>ExpSoupAte</code>)</li>
<li>Consumption volume - Control soup intake (<code>CtrlSoupAte</code>)</li>
<li>
<code>SeatPosition</code> - so we can determine whether participants were sorted into in the Experimental or the Control group</li>
</ul>
<p>Store the new data object as <code>lopez_reduced</code>.</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a>lopez_reduced <span class="ot">&lt;-</span> lopez_included <span class="sc">%&gt;%</span> </span>
<span id="cb4-2"><a href="#cb4-2"></a>  <span class="fu">select</span>(ParticipantID, Sex, OzEstimate, CalEstimate, CtrlSoupAte, ExpSoupAte, SeatPosition)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section><section id="step-3-recoding-the-values" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="step-3-recoding-the-values">Step 3: Recoding the values</h4>
<p>As we can see now, our <code>lopez_reduced</code> data object could use some tidying.</p>
<ol type="1">
<li>
<code>Sex</code> is a categorical variable, yet, it is currently displayed as numeric, which isn’t ideal. Recode these values according to the <code>Soupbowl_data_dictionary</code>. You could either recode the values as we did in <a href="03-wrangling2.html#sec-wrangling2_act3"><span>Section&nbsp;3.3</span></a>) or convert <code>Sex</code> into a factor if that’s easier (see <a href="04-dataviz.html"><span>Chapter&nbsp;4</span></a> for guidance).</li>
<li>
<code>ParticipantID</code> should also be converted into a factor (see <a href="04-dataviz.html"><span>Chapter&nbsp;4</span></a> for guidance).</li>
<li>Create a new variable called <code>Condition</code> to indicate whether participants are in the Control or Experimental group. Use the <code>Soupbowl_data_dictionary</code> o determine which <code>SeatPosition</code> corresponds to normal bowls (Control) and self-refilling bowls (Experimental). If you’re unsure which function to use, refer to <a href="03-wrangling2.html#sec-wrangling2_act4"><span>Section&nbsp;3.4</span></a>.</li>
<li>
<code>CtrlSoupAte</code> and <code>ExpSoupAte</code> can remain separate if we want to focus on these two conditions individually, as we can remove missing values later. However, to calculate correlations across the whole sample, we need these “SoupAte” values in a single column instead of two. We will name this coalesced variable <code>M_postsoup</code> to align with the <code>Soupbowl_data_dictionary</code>.</li>
</ol>
<p>You should be able to complete recoding tasks 1, 2, and 3 on your own. However, Task 4 involves a new function, so we will walk through it together.</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution for Recoding tasks 1-3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>In the panels below, I have created new variables in <code>lopez_reduced</code> to show you solutions for both the <code>case_match()</code> and the <code><a href="https://rdrr.io/r/base/factor.html">factor()</a></code> approach for recoding <code>Sex</code>. Alternatively, you could simply name your new column <code>Sex</code> to overwrite the numeric values in the existing <code>Sex</code> column.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset" data-group="layers">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" aria-current="page">Sex with <code>case_match()</code></a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Sex with <code>factor()</code></a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false">ParticipantID with <code>factor()</code></a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-4" role="tab" aria-controls="tabset-1-4" aria-selected="false">Condition with <code>case_when()</code></a></li>
</ul>
<div class="tab-content" data-group="layers">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<p>Since no conditional statement is needed, a simple <code>case_match()</code> will suffice. This will create a character column.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a>lopez_reduced <span class="ot">&lt;-</span> lopez_reduced <span class="sc">%&gt;%</span> </span>
<span id="cb5-2"><a href="#cb5-2"></a>  <span class="fu">mutate</span>(<span class="at">Sex_case_match =</span> <span class="fu">case_match</span>(Sex,</span>
<span id="cb5-3"><a href="#cb5-3"></a>                                     <span class="dv">0</span> <span class="sc">~</span> <span class="st">"Male"</span>,</span>
<span id="cb5-4"><a href="#cb5-4"></a>                                     <span class="dv">1</span> <span class="sc">~</span> <span class="st">"Female"</span>,</span>
<span id="cb5-5"><a href="#cb5-5"></a>                                     <span class="dv">2</span> <span class="sc">~</span> <span class="st">"Other"</span>,</span>
<span id="cb5-6"><a href="#cb5-6"></a>                                     <span class="dv">3</span> <span class="sc">~</span> <span class="st">"Prefer not to say"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<p>Using a factor is helpful if you want to reorder the labels simultaneously. This will create a factor column.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a>lopez_reduced <span class="ot">&lt;-</span> lopez_reduced <span class="sc">%&gt;%</span> </span>
<span id="cb6-2"><a href="#cb6-2"></a>  <span class="fu">mutate</span>(<span class="at">Sex_factor =</span> <span class="fu">factor</span>(Sex,</span>
<span id="cb6-3"><a href="#cb6-3"></a>                         <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">2</span>, <span class="dv">3</span>),</span>
<span id="cb6-4"><a href="#cb6-4"></a>                         <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Female"</span>, <span class="st">"Male"</span>, <span class="st">"Other"</span>, <span class="st">"Prefer not to say"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<p>There is not much to it, as the levels and labels don’t need changing.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a>lopez_reduced <span class="ot">&lt;-</span> lopez_reduced <span class="sc">%&gt;%</span> </span>
<span id="cb7-2"><a href="#cb7-2"></a>  <span class="fu">mutate</span>(<span class="at">ParticipantID =</span> <span class="fu">factor</span>(ParticipantID))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-1-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-4-tab">
<p>According to the <code>Soupbowl_data_dictionary</code>, even numbers in <code>SeatPosition</code> indicate the Experimental group, and odd numbers represent the Control group. Here we will need to use <code>case_when()</code> because <strong>conditional statements</strong> (see <a href="03-wrangling2.html"><span>Chapter&nbsp;3</span></a> Activity 4 for a refresher).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a>lopez_reduced <span class="ot">&lt;-</span> lopez_reduced <span class="sc">%&gt;%</span> </span>
<span id="cb8-2"><a href="#cb8-2"></a>  <span class="fu">mutate</span>(<span class="at">Condition =</span> <span class="fu">case_when</span>(</span>
<span id="cb8-3"><a href="#cb8-3"></a>    SeatPosition <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>) <span class="sc">~</span> <span class="st">"Control"</span>,</span>
<span id="cb8-4"><a href="#cb8-4"></a>    SeatPosition <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">4</span>) <span class="sc">~</span> <span class="st">"Experimental"</span></span>
<span id="cb8-5"><a href="#cb8-5"></a>  ))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>In the code, I specified 1 and 3 should be labelled “Control” and 2 and 4 “Experimental”. I could have used with the <code>.default =</code> argument for the even seat numbers, however, this requires being certain that all other values are either 2 or 4 (e.g., no invalid numbers like 5 or missing values). Since I did not check beforehand, any value that is not 1, 2, 3, or 4 will remain unlabelled, making it easier to identify and address.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<p>We want to combine the values from <code>CtrlSoupAte</code> and <code>ExpSoupAte</code> into a single column named <code>M_postsoup</code>. <em>(No idea why the authors called it <code>M_postsoup</code> rather than <code>AllSoupAte</code>. However, since this was one of the columns deleted from the original dataset earlier, we’ll stick with the original variable name as the authors intended.)</em></p>
<p>Recoding task 4 is straightforward with a function like <code>coalesce()</code>. For each row, it checks the specified columns and finds the first non-missing value at each position. Essentially, R scans the columns row by row, looking for the first available value that isn’t missing and assigns it to the new column. For example:</p>
<ul>
<li>Participant 1001 has no value in <code>CtrlSoupAte</code> but has a value in <code>ExpSoupAte</code>, so R skips the missing value and assigns 4.5 to the new column.</li>
<li>Participant 1002 has a value in CtrlSoupAte (3.3), directly assigns it to the new column, and so on.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a>lopez_reduced <span class="ot">&lt;-</span> lopez_reduced <span class="sc">%&gt;%</span> </span>
<span id="cb9-2"><a href="#cb9-2"></a>  <span class="fu">mutate</span>(<span class="at">M_postsoup =</span> <span class="fu">coalesce</span>(CtrlSoupAte, ExpSoupAte))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As always, all these “preparing the dataframe” steps could have been combined into a single pipe.</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution for Activity 4 in a single pipe
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a>lopez_reduced <span class="ot">&lt;-</span> lopez_data <span class="sc">%&gt;%</span> </span>
<span id="cb10-2"><a href="#cb10-2"></a>  <span class="co"># Step 1</span></span>
<span id="cb10-3"><a href="#cb10-3"></a>  <span class="fu">filter</span>(Included <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb10-4"><a href="#cb10-4"></a>  <span class="co">#Step 2</span></span>
<span id="cb10-5"><a href="#cb10-5"></a>  <span class="fu">select</span>(ParticipantID, Age, Sex, OzEstimate, CalEstimate, CtrlSoupAte, ExpSoupAte, SeatPosition) <span class="sc">%&gt;%</span> </span>
<span id="cb10-6"><a href="#cb10-6"></a>  <span class="co"># Step 3 (I decided to use the factor approach and override my `Sex` column and include it all into the same `mutate()` function)</span></span>
<span id="cb10-7"><a href="#cb10-7"></a>  <span class="fu">mutate</span>(<span class="at">Sex =</span> <span class="fu">factor</span>(Sex,</span>
<span id="cb10-8"><a href="#cb10-8"></a>                      <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">2</span>, <span class="dv">3</span>),</span>
<span id="cb10-9"><a href="#cb10-9"></a>                      <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Female"</span>, <span class="st">"Male"</span>, <span class="st">"Other"</span>, <span class="st">"Prefer not to say"</span>)),</span>
<span id="cb10-10"><a href="#cb10-10"></a>         <span class="at">ParticipantID =</span> <span class="fu">factor</span>(ParticipantID),</span>
<span id="cb10-11"><a href="#cb10-11"></a>         <span class="at">Condition =</span> <span class="fu">case_when</span>(</span>
<span id="cb10-12"><a href="#cb10-12"></a>           SeatPosition <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>) <span class="sc">~</span> <span class="st">"Control"</span>,</span>
<span id="cb10-13"><a href="#cb10-13"></a>           SeatPosition <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">4</span>) <span class="sc">~</span> <span class="st">"Experimental"</span>),</span>
<span id="cb10-14"><a href="#cb10-14"></a>         <span class="co"># Step 4</span></span>
<span id="cb10-15"><a href="#cb10-15"></a>         <span class="at">M_postsoup =</span> <span class="fu">coalesce</span>(CtrlSoupAte, ExpSoupAte))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section></section><section id="activity-5-compute-descriptives" class="level2" data-number="9.5"><h2 data-number="9.5" class="anchored" data-anchor-id="activity-5-compute-descriptives">
<span class="header-section-number">9.5</span> Activity 5: Compute descriptives</h2>
<p>Now that the data is ready, we can focus on reproducing the correlations. For the remainder of this chapter, we will focus on <strong>correlating the estimated calories of soup consumption with actual consumption volume</strong> for the <strong>control group</strong>. Testing every correlation would require assessing assumptions for each relationship, making this chapter unnecessarily long. However, you are welcome to reproduce all other correlations in your own time if you wish.</p>
<p>For the <strong>descriptives</strong>, we will compute the number of participants (<strong>n</strong>), <strong>means</strong> and <strong>standard deviations</strong> for the <code>Control</code> group of our variables of interest (i.e., <code>CalEstimate</code> and <code>M_postsoup</code>).</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hints
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Filter the data to include only the Control group and focus on the two variables of interest (<code>CalEstimate</code> and <code>M_postsoup</code>), and keep the <code>ParticipantID</code>. You may want to store the data as a new object named <code>lopez_control</code>.</li>
<li>Watch out for missing values in some of the columns. We will address them later during the correlation analysis. For now, instruct R to ignore missing values when calculating descriptive statistics.</li>
</ul>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a><span class="do">## data object lopez_control</span></span>
<span id="cb11-2"><a href="#cb11-2"></a>lopez_control <span class="ot">&lt;-</span> lopez_reduced <span class="sc">%&gt;%</span> </span>
<span id="cb11-3"><a href="#cb11-3"></a>  <span class="fu">filter</span>(Condition <span class="sc">==</span> <span class="st">"Control"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb11-4"><a href="#cb11-4"></a>  <span class="fu">select</span>(ParticipantID, CalEstimate, M_postsoup)</span>
<span id="cb11-5"><a href="#cb11-5"></a></span>
<span id="cb11-6"><a href="#cb11-6"></a><span class="co"># descriptives for lopez_control</span></span>
<span id="cb11-7"><a href="#cb11-7"></a>descriptives_control <span class="ot">&lt;-</span> lopez_control <span class="sc">%&gt;%</span> </span>
<span id="cb11-8"><a href="#cb11-8"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb11-9"><a href="#cb11-9"></a>            <span class="at">mean_CalEstimate =</span> <span class="fu">mean</span>(CalEstimate, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb11-10"><a href="#cb11-10"></a>            <span class="at">sd_CalEstimate =</span> <span class="fu">sd</span>(CalEstimate, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb11-11"><a href="#cb11-11"></a>            <span class="at">mean_M_postsoup =</span> <span class="fu">mean</span>(M_postsoup),</span>
<span id="cb11-12"><a href="#cb11-12"></a>            <span class="at">sd_M_postsoup =</span> <span class="fu">sd</span>(M_postsoup)) <span class="sc">%&gt;%</span> </span>
<span id="cb11-13"><a href="#cb11-13"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb11-14"><a href="#cb11-14"></a></span>
<span id="cb11-15"><a href="#cb11-15"></a>descriptives_control</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: right;">n</th>
<th style="text-align: right;">mean_CalEstimate</th>
<th style="text-align: right;">sd_CalEstimate</th>
<th style="text-align: right;">mean_M_postsoup</th>
<th style="text-align: right;">sd_M_postsoup</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: right;">246</td>
<td style="text-align: right;">133.0328</td>
<td style="text-align: right;">121.3261</td>
<td style="text-align: right;">8.86748</td>
<td style="text-align: right;">6.236679</td>
</tr></tbody>
</table>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</section><section id="activity-6-create-an-appropriate-plot" class="level2" data-number="9.6"><h2 data-number="9.6" class="anchored" data-anchor-id="activity-6-create-an-appropriate-plot">
<span class="header-section-number">9.6</span> Activity 6: Create an appropriate plot</h2>
<p>The only option for a correlation is a <select class="webex-select"><option value="blank"></option>
<option value="x">stacked barchart</option>
<option value="x">histogram</option>
<option value="answer">scatterplot</option>
<option value="x">violin-boxplot</option></select> because <select class="webex-select"><option value="blank"></option>
<option value="x">both variables are categorical</option>
<option value="answer">both variables are continuous</option>
<option value="x">one variable is continuous and the other categorical</option>
<option value="x">There is only one variable and it’s continuous</option></select>.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Your Turn
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Create an appropriate plot to visualise the relationship between <code>CalEstimate</code> and <code>M_postsoup</code>.</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution for the plot
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a><span class="fu">ggplot</span>(lopez_control, <span class="fu">aes</span>(<span class="at">x =</span> CalEstimate, <span class="at">y =</span> M_postsoup)) <span class="sc">+</span></span>
<span id="cb12-2"><a href="#cb12-2"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="09-correlation_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</section><section id="activity-7-check-assumptions" class="level2" data-number="9.7"><h2 data-number="9.7" class="anchored" data-anchor-id="activity-7-check-assumptions">
<span class="header-section-number">9.7</span> Activity 7: Check assumptions</h2>
<section id="assumption-1-continuous-variables" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="assumption-1-continuous-variables">Assumption 1: Continuous variables</h4>
<p>Both variables must be measured at the <strong>interval or ratio</strong> level (i.e., continuous data). We can confirm this by examining our two variables of interest, <code>CalEstimate</code> and <code>M_postsoup</code>. Plus, you would already know whether the variables are continuous based on your study design.</p>
</section><section id="assumption-2-related-pairs" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="assumption-2-related-pairs">Assumption 2: Related pairs</h4>
<p>Each participant needs to have <strong>2 data points</strong>, in our case one value for <code>CalEstimate</code> and one for <code>M_postsoup</code>. You can verify this directly in the dataset (e.g., <code>lopez_control</code>) or watch for warning messages when creating the scatterplot.</p>
<p>In this dataset, there are no missing values in <code>M_postsoup</code> but <code>CalEstimate</code> has two missing values. hmmm. Interestingly, the Lopez paper mentions exclusion criteria in the Supplementary Materials but only in relation to participants, not statistical exclusions.</p>
<p>Technically, incomplete pairs won’t appear in the scatterplot and will be automatically excluded during the correlation analysis (as we will observe later). However, in the interest of transparency, any data exclusions should be clearly stated in your reports.</p>
<p>To address this, we can also exclude the missing values from <code>lopez_control</code>. Here, I’m using the <code>drop_na()</code> function to remove rows with missing data. I will save this as a new data object <code>lopez_control_no_na</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a>lopez_control_no_na <span class="ot">&lt;-</span> lopez_control <span class="sc">%&gt;%</span> </span>
<span id="cb16-2"><a href="#cb16-2"></a>  <span class="fu">drop_na</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Data from participants 1895 and 1908 has now been excluded, leaving us with complete pairs. The assumption holds.</p>
</section><section id="assumption-3-independence-of-casesobservations" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="assumption-3-independence-of-casesobservations">Assumption 3: Independence of cases/observations</h4>
<p>Similar to the paired t-test, we must assume that the two <strong>observations for each case are independent</strong> of the observations for any other case. This basically means that participants did not influence each other’s ratings. Once again, this assumption is related to the study design and is satisfied in this instance.</p>
</section><section id="assumption-4-linearity" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="assumption-4-linearity">Assumption 4: Linearity</h4>
<p>To run a Pearson correlation, the relationship between the two variables must be linear.</p>
<p>You can assess linearity visually using a <strong>Residuals vs Fitted plot</strong>, which can be generated by applying the <code><a href="https://rdrr.io/r/graphics/plot.default.html">plot()</a></code> function to a linear model (<code>lm</code>) object. The function requires the following arguments:</p>
<ul>
<li>The 2 variables of interest, separated by a tilde (<code>~</code>)</li>
<li>The dataset</li>
<li>The <code>which</code> argument specifies which plot we want to show. Number 1 will produce a Residuals vs Fitted plot.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1"></a><span class="fu">plot</span>(<span class="fu">lm</span>(CalEstimate<span class="sc">~</span>M_postsoup, <span class="at">data =</span> lopez_control_no_na), <span class="at">which =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="09-correlation_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Alternative
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>You can also assess linearity using a scatterplot, but instead of fitting a linear model “lm”, use the “loess” method for the line of best fit. Then, examine how closely the resulting line resembles a linear line.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a><span class="fu">ggplot</span>(lopez_control_no_na, <span class="fu">aes</span>(<span class="at">x =</span> CalEstimate, <span class="at">y =</span> M_postsoup)) <span class="sc">+</span></span>
<span id="cb18-2"><a href="#cb18-2"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb18-3"><a href="#cb18-3"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="09-correlation_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
</div>
<p><strong>Verdict:</strong> This does actually look non-linear to me. The original authors did not mention any assumption testing in their paper or Supplementary Materials. If they conducted these tests, we can assume they deemed the assumptions satisfied.</p>
</section><section id="assumption-5-normality" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="assumption-5-normality">Assumption 5: Normality</h4>
<p>Residuals for both variables should follow a <strong>bivariate normal distribution</strong> (i.e., both together normally distributed). We can use a <strong>Q-Q plot</strong> to visually check this assumptions. The code is the same as above (i.e., <code><a href="https://rdrr.io/r/graphics/plot.default.html">plot()</a></code> with <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code>), but this time, set the <code>which</code> argument to 2 to generate the Q-Q plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a><span class="fu">plot</span>(<span class="fu">lm</span>(CalEstimate<span class="sc">~</span>M_postsoup, <span class="at">data =</span> lopez_control_no_na), <span class="at">which =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="09-correlation_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Alternatives
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="tabset-margin-container"></div><div class="panel-tabset" data-group="layers">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true">Option 1: plotting both variables individually</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false">Option 2: Scatterplot</a></li>
</ul>
<div class="tab-content" data-group="layers">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<p>In practice it is frequently accepted that each variable is normally distributed rather than both together (i.e., <strong>univariate normality</strong>). However, there is some disagreement among experts whether Pearson’s correlation is “robust” to violations of univariate normality. Anyway, we are showing this approach as an alternative using the Q-Q plot version with packages <code>ggplot</code> and <code>qqplotr</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1"></a><span class="fu">ggplot</span>(lopez_control_no_na, <span class="fu">aes</span>(<span class="at">sample =</span> CalEstimate)) <span class="sc">+</span></span>
<span id="cb21-2"><a href="#cb21-2"></a>  <span class="fu">stat_qq_band</span>(<span class="at">fill =</span> <span class="st">"#FB8D61"</span>, <span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3"></a>  <span class="fu">stat_qq_line</span>(<span class="at">colour =</span> <span class="st">"#FB8D61"</span>) <span class="sc">+</span></span>
<span id="cb21-4"><a href="#cb21-4"></a>  <span class="fu">stat_qq_point</span>()</span>
<span id="cb21-5"><a href="#cb21-5"></a></span>
<span id="cb21-6"><a href="#cb21-6"></a><span class="fu">ggplot</span>(lopez_control_no_na, <span class="fu">aes</span>(<span class="at">sample =</span> M_postsoup)) <span class="sc">+</span></span>
<span id="cb21-7"><a href="#cb21-7"></a>  <span class="fu">stat_qq_band</span>(<span class="at">fill =</span> <span class="st">"#FB8D61"</span>, <span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb21-8"><a href="#cb21-8"></a>  <span class="fu">stat_qq_line</span>(<span class="at">colour =</span> <span class="st">"#FB8D61"</span>) <span class="sc">+</span></span>
<span id="cb21-9"><a href="#cb21-9"></a>  <span class="fu">stat_qq_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-bins" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="09-correlation_files/figure-html/fig-bins-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;9.1: Bins vs binwidth arguments</figcaption></figure>
</div>
</div>
</div>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<p>We can also use the function <code>ggMarginal()</code> to enhance a ggplot2 scatterplot by adding marginal density plots, histograms, or boxplots. The workflow is slightly different: first, save the scatterplot as a data object, then apply <code>ggMarginal()</code> to that object.</p>
<p>To customise the marginal plots:</p>
<ul>
<li>Use <code>type = "histogram"</code> for histograms.</li>
<li>Use <code>type = "boxplot"</code> for boxplots.</li>
<li>Leave the <code>type</code> argument out or set it to <code>type = "density"</code> to display the default density plots.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(lopez_control_no_na, <span class="fu">aes</span>(<span class="at">x =</span> CalEstimate, <span class="at">y =</span> M_postsoup)) <span class="sc">+</span></span>
<span id="cb22-2"><a href="#cb22-2"></a>  <span class="fu">geom_point</span>()</span>
<span id="cb22-3"><a href="#cb22-3"></a></span>
<span id="cb22-4"><a href="#cb22-4"></a><span class="fu">ggMarginal</span>(p1, <span class="at">type =</span> <span class="st">"density"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="09-correlation_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>More info here: <a href="https://cran.r-project.org/web/packages/ggExtra/vignettes/ggExtra.html" target="_blank">https://cran.r-project.org/web/packages/ggExtra/vignettes/ggExtra.html</a></p>
</div>
</div>
</div>
</div>
</div>
</div>
<p><strong>Verdict:</strong> For me, the assumption of normality would not hold, whether assessed jointly or independently, as the points follow a curve rather than “hugging” the straight line with potentially some potential deviations in the tails. However, I seem to be more conservative in my judgements compared to Lopez et al.&nbsp;Since they proceeded with a Pearson correlation, the assumption must have held for them.</p>
</section><section id="assumption-6-homoscedasticity" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="assumption-6-homoscedasticity">Assumption 6: Homoscedasticity</h4>
<p>Homoscedasticity assumes that the data is evenly distributed around the line of best fit, with no visible pattern. This assumption can be assessed visually using a <strong>Scale-Location plot</strong> or directly within the scatterplot.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset" data-group="layers">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true">Option 1: Scale-Location plot</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false">Option 2: Scatterplot</a></li>
</ul>
<div class="tab-content" data-group="layers">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<p>As you might have guessed, we will use the <code><a href="https://rdrr.io/r/graphics/plot.default.html">plot()</a></code> function with <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> again but this time set the <code>which</code> argument to 3 to generate the Scale-Location plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1"></a><span class="fu">plot</span>(<span class="fu">lm</span>(CalEstimate<span class="sc">~</span>M_postsoup, <span class="at">data =</span> lopez_control_no_na), <span class="at">which =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="09-correlation_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<p>We will use the same scatterplot as above, but this time focus on the points and their distance from the blue line. If the points are randomly scattered around the line of best fit, the assumption holds. However, if a distinct pattern emerges, the assumption is violated.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a><span class="fu">ggplot</span>(lopez_control_no_na, <span class="fu">aes</span>(<span class="at">x =</span> CalEstimate, <span class="at">y =</span> M_postsoup)) <span class="sc">+</span></span>
<span id="cb24-2"><a href="#cb24-2"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb24-3"><a href="#cb24-3"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="09-correlation_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
</div>
<p><strong>Verdict:</strong> This is another assumption that feels borderline to me. There appears to be slight heteroscedasticity. In the Scale-Location plot, the red line should ideally be flat and horizontal, but ours has a slight slope and could be flatter. If you prefer looking at the scatterplot, you can observe the data points moving slightly further away from the line of best fit as the x and y values increase. this is kinda forming a slight funnel shape rather than the roughly random spread of data points shown in last week’s lecture slides. Nevertheless, the authors took a more lenient approach and considered the assumption to be met.</p>
</section><section id="assumption-7-absence-of-outliers" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="assumption-7-absence-of-outliers">Assumption 7: Absence of outliers</h4>
<p>Ideally, our data should not contain any outliers or influential points, as these can distort the relationship between the variables of interest. We can assess this assumption visually with a <strong>Residuals vs Leverage plot</strong> or by revisiting the scatterplot (as shown above).</p>
<div class="tabset-margin-container"></div><div class="panel-tabset" data-group="layers">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true">Option 1: Residuals vs Leverage plot</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-2" role="tab" aria-controls="tabset-4-2" aria-selected="false">Option 2: Scatterplot</a></li>
</ul>
<div class="tab-content" data-group="layers">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<p>To identify those data points, we can look at plot 5 from the <code><a href="https://rdrr.io/r/graphics/plot.default.html">plot()</a></code> function with the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> object but setting the <code>which</code> argument to 5.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a><span class="fu">plot</span>(<span class="fu">lm</span>(CalEstimate<span class="sc">~</span>M_postsoup, <span class="at">data =</span> lopez_control_no_na), <span class="at">which =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="09-correlation_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Here, case numbers 3, 183, and 205 are identified. In the data object <code>lopez_control_no_na</code>, these correspond to participant IDs 1007, 1716, and 1789, respectively. Two of these participants estimated they had consumed 800 calories, while the third data point has a y-value over 40 (the one with the lower x-value).</p>
</div>
<div id="tabset-4-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-2-tab">
<p>Looking at the scatterplot, I would have probably identified 4 outliers - anyone who estimated more than 600 cal and anyone who consumed more than 40 ounces of soup.</p>
</div>
</div>
</div>
<p><strong>Verdict:</strong> There are several ways to handle outliers, such as excluding them, replacing their extreme values with the group mean, or winsorising them. For now, I would likely exclude these three data points from the dataset before proceeding. However, Lopez et al.&nbsp;chose to retain all data points.</p>
<p><strong>Remember: Any data exclusions in your reports must be clearly justified.</strong></p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Your Turn
</div>
</div>
<div class="callout-body-container callout-body">
<p>Filter out the 3 (or 4) influential points/outliers and create the plot again. It’s best to save the data without outliers as a new data object. I’ve named mine <code>lopez_control_no_outliers</code>, but feel free to use a name that works for you.</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution for removing 3 outliers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1"></a>lopez_control_no_outliers <span class="ot">&lt;-</span> lopez_control_no_na <span class="sc">%&gt;%</span> </span>
<span id="cb27-2"><a href="#cb27-2"></a>  <span class="fu">filter</span>(<span class="sc">!</span>ParticipantID <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1007</span>, <span class="dv">1716</span>, <span class="dv">1789</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1"></a><span class="fu">ggplot</span>(lopez_control_no_outliers, <span class="fu">aes</span>(<span class="at">x =</span> CalEstimate, <span class="at">y =</span> M_postsoup)) <span class="sc">+</span></span>
<span id="cb28-2"><a href="#cb28-2"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="09-correlation_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution for removing 4 outliers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1"></a>lopez_control_no_outliers4 <span class="ot">&lt;-</span> lopez_control_no_na <span class="sc">%&gt;%</span> </span>
<span id="cb30-2"><a href="#cb30-2"></a>  <span class="fu">filter</span>(CalEstimate <span class="sc">&lt;</span> <span class="dv">600</span>,</span>
<span id="cb30-3"><a href="#cb30-3"></a>         M_postsoup <span class="sc">&lt;</span> <span class="dv">40</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1"></a><span class="fu">ggplot</span>(lopez_control_no_outliers4, <span class="fu">aes</span>(<span class="at">x =</span> CalEstimate, <span class="at">y =</span> M_postsoup)) <span class="sc">+</span></span>
<span id="cb31-2"><a href="#cb31-2"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb31-3"><a href="#cb31-3"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="09-correlation_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</section><section id="final-word-on-assumption-checks" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="final-word-on-assumption-checks">Final word on Assumption checks</h4>
<p>For me, there would be enough justification to switch to a non-parametric correlation method, such as Spearman. However, since the original authors ran Pearson correlations, we will follow their approach in Activity 8. We will also revert to the data object <code>lopez_control</code>, as the original authors chose not to exclude any data points (e.g., missing values, outliers, etc.).</p>
</section></section><section id="activity-8-pearsons-correlation-effect-size" class="level2" data-number="9.8"><h2 data-number="9.8" class="anchored" data-anchor-id="activity-8-pearsons-correlation-effect-size">
<span class="header-section-number">9.8</span> Activity 8: Pearson’s correlation &amp; effect size</h2>
<p>There are plenty of options out there to compute a correlation. We will use the <code>correlation()</code> function from the <code>correlation</code> package because it offers more consistent reporting features. The <code>correlation()</code> function requires:</p>
<ul>
<li>The name of the data set you are using.</li>
<li>The name of the first variable you want to select for the correlation.</li>
<li>The name of the second variable you want to select for the correlation.</li>
<li>The type of correlation you want to run: e.g.&nbsp;Pearson, Spearman.</li>
</ul>
<p>For a two-tailed Pearson correlation using the <code>lopez_control</code> dataset, the code would look like this <em>(note the quotation marks around everything except the data object)</em>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1"></a><span class="fu">correlation</span>(<span class="at">data =</span> lopez_control,</span>
<span id="cb33-2"><a href="#cb33-2"></a>            <span class="at">select =</span> <span class="st">"CalEstimate"</span>,</span>
<span id="cb33-3"><a href="#cb33-3"></a>            <span class="at">select2 =</span> <span class="st">"M_postsoup"</span>,</span>
<span id="cb33-4"><a href="#cb33-4"></a>            <span class="at">method =</span> <span class="st">"Pearson"</span>,</span>
<span id="cb33-5"><a href="#cb33-5"></a>            <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 4%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 2%">
<col style="width: 19%">
<col style="width: 5%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">Parameter1</th>
<th style="text-align: left;">Parameter2</th>
<th style="text-align: right;">r</th>
<th style="text-align: right;">CI</th>
<th style="text-align: right;">CI_low</th>
<th style="text-align: right;">CI_high</th>
<th style="text-align: right;">t</th>
<th style="text-align: right;">df_error</th>
<th style="text-align: right;">p</th>
<th style="text-align: left;">Method</th>
<th style="text-align: right;">n_Obs</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: left;">CalEstimate</td>
<td style="text-align: left;">M_postsoup</td>
<td style="text-align: right;">0.4045319</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">0.293876</td>
<td style="text-align: right;">0.5044879</td>
<td style="text-align: right;">6.881219</td>
<td style="text-align: right;">242</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Pearson correlation</td>
<td style="text-align: right;">244</td>
</tr></tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Since <code>lopez_control</code> contains only three variables and we’ve already converted <code>ParticipantID</code> into a factor, we can pass the entire data object to the <code>correlation()</code> function. This will compute correlations between all numeric columns in the dataset. In this case, it would result in just one association, but see below for an example with more numeric variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1"></a><span class="fu">correlation</span>(lopez_control)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 4%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 2%">
<col style="width: 19%">
<col style="width: 5%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">Parameter1</th>
<th style="text-align: left;">Parameter2</th>
<th style="text-align: right;">r</th>
<th style="text-align: right;">CI</th>
<th style="text-align: right;">CI_low</th>
<th style="text-align: right;">CI_high</th>
<th style="text-align: right;">t</th>
<th style="text-align: right;">df_error</th>
<th style="text-align: right;">p</th>
<th style="text-align: left;">Method</th>
<th style="text-align: right;">n_Obs</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: left;">CalEstimate</td>
<td style="text-align: left;">M_postsoup</td>
<td style="text-align: right;">0.4045319</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">0.293876</td>
<td style="text-align: right;">0.5044879</td>
<td style="text-align: right;">6.881219</td>
<td style="text-align: right;">242</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Pearson correlation</td>
<td style="text-align: right;">244</td>
</tr></tbody>
</table>
</div>
</div>
</div>
</div>
</div>
<p>Here we obtained a Pearson correlation value of .405 which is close to the value of .41 reported by Lopez et al.&nbsp;(2024). Remember to report correlation values to three decimal places to adhere to APA style (though the journal in this case may have followed different guidelines).</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Correlation Matrix - more than 1 comparison
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>If you want to correlate multiple variables with one another, you can do that in a correlation matrix.</p>
<p>Let’s try to replicate the correlations for full sample:</p>
<ul>
<li>
<code>OzEstimate</code> and <code>CalEstimate</code>,</li>
<li>
<code>OzEstimate</code> and <code>M_postsoup</code>, and</li>
<li>
<code>CalEstimate</code> and <code>M_postsoup</code>.</li>
</ul>
<p>To do this, first ensure that only the relevant variables are selected and that a variable like <code>ParticipantID</code> is converted into a factor. I have stored all four variables in an object called <code>lopez_overall</code>.</p>
<p>You can also include an additional argument, <code>p_adjust</code>, to specify the type of correction you want to apply for multiple comparisons (e.g., “Bonferroni”). If you don’t include the <code>p_adjust</code> argument, the default method will be “Holm”. In either case, the correction method will be listed in the output.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1"></a>lopez_overall <span class="ot">&lt;-</span> lopez_reduced <span class="sc">%&gt;%</span> </span>
<span id="cb35-2"><a href="#cb35-2"></a>  <span class="fu">select</span>(ParticipantID, OzEstimate, CalEstimate, M_postsoup)</span>
<span id="cb35-3"><a href="#cb35-3"></a></span>
<span id="cb35-4"><a href="#cb35-4"></a><span class="fu">correlation</span>(lopez_overall, <span class="at">p_adjust =</span> <span class="st">"bonferroni"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 9%">
<col style="width: 4%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 5%">
<col style="width: 18%">
<col style="width: 5%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">Parameter1</th>
<th style="text-align: left;">Parameter2</th>
<th style="text-align: right;">r</th>
<th style="text-align: right;">CI</th>
<th style="text-align: right;">CI_low</th>
<th style="text-align: right;">CI_high</th>
<th style="text-align: right;">t</th>
<th style="text-align: right;">df_error</th>
<th style="text-align: right;">p</th>
<th style="text-align: left;">Method</th>
<th style="text-align: right;">n_Obs</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">OzEstimate</td>
<td style="text-align: left;">CalEstimate</td>
<td style="text-align: right;">0.2575243</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">0.1700045</td>
<td style="text-align: right;">0.3410133</td>
<td style="text-align: right;">5.697404</td>
<td style="text-align: right;">457</td>
<td style="text-align: right;">1e-07</td>
<td style="text-align: left;">Pearson correlation</td>
<td style="text-align: right;">459</td>
</tr>
<tr class="even">
<td style="text-align: left;">OzEstimate</td>
<td style="text-align: left;">M_postsoup</td>
<td style="text-align: right;">0.2829064</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">0.1967556</td>
<td style="text-align: right;">0.3647221</td>
<td style="text-align: right;">6.326103</td>
<td style="text-align: right;">460</td>
<td style="text-align: right;">0e+00</td>
<td style="text-align: left;">Pearson correlation</td>
<td style="text-align: right;">462</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CalEstimate</td>
<td style="text-align: left;">M_postsoup</td>
<td style="text-align: right;">0.3611089</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">0.2789816</td>
<td style="text-align: right;">0.4379921</td>
<td style="text-align: right;">8.296305</td>
<td style="text-align: right;">459</td>
<td style="text-align: right;">0e+00</td>
<td style="text-align: left;">Pearson correlation</td>
<td style="text-align: right;">461</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>When running the code in the .Rmd file, the correction method is displayed beneath the table in the printout. However, when the document is knitted into HTML, this information does not appear.</p>
<p>However, in the knitted document, the output also includes the number of observations for each row, whereas the .Rmd printout only displays the <em>range of observation</em> values beneath the table.</p>
<p>Similarly, p-values are displayed in APA style (e.g., <em>p</em> &lt; .001) in the .Rmd printout, but in the knitted document, they may appear in scientific notation or as 0. <strong>When reporting p-values in your report, ensure they adhere to APA style.</strong></p>
</div>
</div>
</div>
</div>
</div>
<p><strong>The effect size for correlations does not require additional computation. It is simply the vale of the correlation coefficient <code>r</code>.</strong></p>
</section><section id="activity-9-sensitivity-power-analysis" class="level2" data-number="9.9"><h2 data-number="9.9" class="anchored" data-anchor-id="activity-9-sensitivity-power-analysis">
<span class="header-section-number">9.9</span> Activity 9: Sensitivity power analysis</h2>
<p>As with the t-test, we will conduct a sensitivity power analysis to determine the minimum effect size detectable with our sample of control participants (n = 244, accounting for the two missing values), an alpha level of 0.05, and a power of 0.8. This will help us assess whether our analysis was sufficiently powered.</p>
<p>We will use the <code>pwr.r.test()</code> function from the <code>pwr</code> package for the correlation analysis. As usual, include <code>n</code>, <code>alpha</code>, and <code>power</code> as arguments in the function, and leave out the effect size <code>r</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1"></a><span class="fu">pwr.r.test</span>(<span class="at">n =</span> <span class="dv">244</span>, <span class="at">sig.level =</span> <span class="fl">0.05</span>, <span class="at">power =</span> <span class="fl">0.8</span>, <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     approximate correlation power calculation (arctangh transformation) 

              n = 244
              r = 0.1782315
      sig.level = 0.05
          power = 0.8
    alternative = two.sided</code></pre>
</div>
</div>
<p>According to the output above, the smallest <code>r</code> detectable with 244 participants, a significance level of .05, and a power of .8 is .178. Since Lopez et al.&nbsp;reported an effect size of r = .41, the study was sufficiently powered.</p>
</section><section id="activity-10-the-write-up" class="level2" data-number="9.10"><h2 data-number="9.10" class="anchored" data-anchor-id="activity-10-the-write-up">
<span class="header-section-number">9.10</span> Activity 10: The write-up</h2>
<p>Lopez et al.&nbsp;(2024) hypothesised a positive correlation between estimated calories of soup consumed <span class="math inline">\((M = 133.0 cal, SD = 121.3 cal)\)</span> and actual consumption volume <span class="math inline">\((M = 8.87 oz, SD = 6.24 oz)\)</span>. A Pearson correlation revealed a moderately strong, positive, and statistically significant relationship between these two variables, <span class="math inline">\(r(242) = .405, p &lt; .001, 95\% CI = [.294, .504]\)</span>. The study was sufficiently powered. Lopez et al.&nbsp;rejected the null hypothesis in favour of H<sub>1</sub>.</p>
</section><section id="activity-11-non-parametric-alternative" class="level2" data-number="9.11"><h2 data-number="9.11" class="anchored" data-anchor-id="activity-11-non-parametric-alternative">
<span class="header-section-number">9.11</span> Activity 11: Non-parametric alternative</h2>
<p>Running a Pearson correlation when its assumptions are violated can lead to unreliable and misleading results, meaning the calculated correlation coefficient may not accurately reflect the true relationship between the variables.</p>
<p>The non-parametric alternative is <strong>Spearman’s Rank correlation</strong>. However, Spearman’s correlation also has a few assumptions:</p>
<ul>
<li>Both variables must be measured on <strong>ordinal, interval or ratio scales</strong>.</li>
<li>There must be a <strong>monotonic</strong> relationship between the two variables, meaning they are either positively or negatively correlated. The data points should not display a “U-shape” or an “inverted U-shape”.</li>
</ul>
<p>Let’s assess monotonicity with a scatterplot. Use the “loess” method to fit the curve, as we are not aiming to show a linear relationship this time.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1"></a><span class="fu">ggplot</span>(lopez_control_no_outliers, <span class="fu">aes</span>(<span class="at">x =</span> CalEstimate, <span class="at">y =</span> M_postsoup)) <span class="sc">+</span></span>
<span id="cb38-2"><a href="#cb38-2"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb38-3"><a href="#cb38-3"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="09-correlation_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Verdict:</strong> Both assumptions hold. The line of best fit displays a clear monotonic relationship, especially with the outliers removed. Therefore, we will proceed with Spearman’s correlation.</p>
<p>Before proceeding, we may want to recalculate the descriptives after removing the outliers:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1"></a><span class="co"># descriptives for lopez_control_no_outliers</span></span>
<span id="cb40-2"><a href="#cb40-2"></a>descriptives_control_no_outliers <span class="ot">&lt;-</span> lopez_control_no_outliers <span class="sc">%&gt;%</span> </span>
<span id="cb40-3"><a href="#cb40-3"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb40-4"><a href="#cb40-4"></a>            <span class="at">mean_CalEstimate =</span> <span class="fu">mean</span>(CalEstimate, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb40-5"><a href="#cb40-5"></a>            <span class="at">sd_CalEstimate =</span> <span class="fu">sd</span>(CalEstimate, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb40-6"><a href="#cb40-6"></a>            <span class="at">mean_M_postsoup =</span> <span class="fu">mean</span>(M_postsoup),</span>
<span id="cb40-7"><a href="#cb40-7"></a>            <span class="at">sd_M_postsoup =</span> <span class="fu">sd</span>(M_postsoup)) <span class="sc">%&gt;%</span> </span>
<span id="cb40-8"><a href="#cb40-8"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb40-9"><a href="#cb40-9"></a></span>
<span id="cb40-10"><a href="#cb40-10"></a>descriptives_control_no_outliers</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: right;">n</th>
<th style="text-align: right;">mean_CalEstimate</th>
<th style="text-align: right;">sd_CalEstimate</th>
<th style="text-align: right;">mean_M_postsoup</th>
<th style="text-align: right;">sd_M_postsoup</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: right;">241</td>
<td style="text-align: right;">127.9668</td>
<td style="text-align: right;">105.4418</td>
<td style="text-align: right;">8.684232</td>
<td style="text-align: right;">5.862664</td>
</tr></tbody>
</table>
</div>
</div>
</div>
<p>Next we will move on to the <strong>inferential test</strong>. The code remains the same as above, but this time we will change the method to “Spearman” and use the data object <code>lopez_control_no_outliers</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1"></a><span class="fu">correlation</span>(lopez_control_no_outliers, <span class="at">method =</span> <span class="st">"Spearman"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 12%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 5%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 3%">
<col style="width: 21%">
<col style="width: 6%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">Parameter1</th>
<th style="text-align: left;">Parameter2</th>
<th style="text-align: right;">rho</th>
<th style="text-align: right;">CI</th>
<th style="text-align: right;">CI_low</th>
<th style="text-align: right;">CI_high</th>
<th style="text-align: right;">S</th>
<th style="text-align: right;">p</th>
<th style="text-align: left;">Method</th>
<th style="text-align: right;">n_Obs</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: left;">CalEstimate</td>
<td style="text-align: left;">M_postsoup</td>
<td style="text-align: right;">0.5225186</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">0.4210739</td>
<td style="text-align: right;">0.6110526</td>
<td style="text-align: right;">1113907</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Spearman correlation</td>
<td style="text-align: right;">241</td>
</tr></tbody>
</table>
</div>
</div>
</div>
<p><strong>Writing-up the results</strong> would be similar to the Pearson correlation above.</p>
<p>It was hypothesised that there would be a positive correlation between estimated calories of soup consumed <span class="math inline">\((M = 128.0 cal, SD = 105.4 cal)\)</span> with actual consumption volume <span class="math inline">\((M = 8.68 oz, SD = 5.86 oz)\)</span>. The assumptions of linearity, normality, and homoscedasticity were assessed visually using a Residuals vs Fitted plot, a Q-Q plot, and a Scale-Location plot, respectively. These assumptions did not hold. Additionally, three outliers were removed from the dataset.</p>
<p>Consequently, a Spearman’s rank correlation was conducted, revealing a strong, positive, and statistically significant relationship between estimated calories of soup consumed and actual consumption volume, <span class="math inline">\(rho(239) = .522, p &lt; .001, 95\% CI = [.421, .611]\)</span>. The study was sufficiently powered. Therefore, the null hypothesis is rejected in favour of H<sub>1</sub>.</p>
</section><section id="test-your-knowledge" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="test-your-knowledge"><span style="color: #F39C12; text-transform: uppercase;">Test your knowledge</span></h2>
<section id="question-1" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="question-1">Question 1</h4>
<p><strong>What is the main purpose of a Pearson correlation?</strong></p>
<div id="radio_JJZEZOPLHO" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_JJZEZOPLHO" value="answer"><span>To assess the strength and direction of a linear relationship between two continuous variables.</span></label><label><input type="radio" autocomplete="off" name="radio_JJZEZOPLHO" value="x"><span>To compare the means of two independent groups.</span></label><label><input type="radio" autocomplete="off" name="radio_JJZEZOPLHO" value="x"><span>To determine the monotonic relationship between two ordinal variables.</span></label><label><input type="radio" autocomplete="off" name="radio_JJZEZOPLHO" value="x"><span>To test for differences in variances between two continuous variables.</span></label>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Explain this answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>“To assess the strength and direction of a linear relationship between two continuous variables.”</strong> is the correct answer.</p>
<p><strong>The other options are incorrect:</strong></p>
<ul>
<li><p><strong>“To compare the means of two independent groups”</strong> is incorrect because that describes an independent t-test, not correlation.</p></li>
<li><p><strong>“To determine the monotonic relationship between two ordinal variables”</strong> is incorrect because that describes Spearman’s correlation, not Pearson’s.</p></li>
<li><p><strong>“To test for differences in variances between two continuous variables”</strong> is incorrect because that refers to Levene’s test or similar, not correlation.</p></li>
</ul>
</div>
</div>
</div>
</section><section id="question-2" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="question-2">Question 2</h4>
<p><strong>Which of the following is a key assumption of the Pearson correlation?</strong></p>
<div id="radio_NWQBKEKTPG" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_NWQBKEKTPG" value="x"><span>The test is robust against outliers.</span></label><label><input type="radio" autocomplete="off" name="radio_NWQBKEKTPG" value="x"><span>The two variables are measured on an ordinal, interval, or ratio scale</span></label><label><input type="radio" autocomplete="off" name="radio_NWQBKEKTPG" value="x"><span>The dependent variable is continuous.</span></label><label><input type="radio" autocomplete="off" name="radio_NWQBKEKTPG" value="answer"><span>The relationship between the two variables is linear.</span></label>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-22-contents" aria-controls="callout-22" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Explain this answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-22" class="callout-22-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Pearson correlation assumes linearity.</p>
<p><strong>The other options are incorrect: </strong></p>
<ul>
<li><p><strong>“The two variables are measured on a ordinal scale”</strong> is incorrect because Pearson correlation requires interval or ratio data, but for ordinal data you would have to switch to the non-parametric equivalent (i.e.&nbsp;“Spearman”).</p></li>
<li><p><strong>“The dependent variable is continuous”</strong> is incorrect because there are no dependent and independent variables in a correlation. The variables are called “measured variables” or just “variables”. And both of them need to be measured on a continuous scale.</p></li>
<li><p><strong>“The test is robust against outliers”</strong> is incorrect because outliers can strongly influence the Pearson correlation coefficient, making it less robust in their presence.</p></li>
</ul>
</div>
</div>
</div>
</section><section id="question-3" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="question-3">Question 3</h4>
<p><strong>You perform a Pearson correlation and find <span class="math inline">\(r(244) = .415, p = .002\)</span>. How would you interpret these results??</strong></p>
<div id="radio_ZHKKXPWKSQ" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_ZHKKXPWKSQ" value="x"><span>There is a moderate, positive, statistically non-significant correlation between the two variables.</span></label><label><input type="radio" autocomplete="off" name="radio_ZHKKXPWKSQ" value="x"><span>There is a moderate, negative, statistically non-significant correlation between the two variables.</span></label><label><input type="radio" autocomplete="off" name="radio_ZHKKXPWKSQ" value="x"><span>There is a moderate, negative, statistically significant correlation between the two variables.</span></label><label><input type="radio" autocomplete="off" name="radio_ZHKKXPWKSQ" value="answer"><span>There is a moderate, positive, statistically significant correlation between the two variables.</span></label>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-23-contents" aria-controls="callout-23" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Explain this answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-23" class="callout-23-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>“There is a moderate, positive, statistically significant correlation between the two variables.”</strong> is the correct answer. The correlation value (<span class="math inline">\(r=.415\)</span>) indicates a moderate, positive relationship, and the p-value (<span class="math inline">\(p=.002\)</span>) indicates statistical significance.</p>
</div>
</div>
</div>
</section><section id="question-4" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="question-4">Question 4</h4>
<p><strong>What does a Spearman correlation coefficient of <span class="math inline">\(rho = -.729\)</span> indicate?</strong></p>
<div id="radio_NGNEPQIQJN" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_NGNEPQIQJN" value="x"><span>A strong, negative linear relationship.</span></label><label><input type="radio" autocomplete="off" name="radio_NGNEPQIQJN" value="x"><span>A strong, positive monotonic relationship.</span></label><label><input type="radio" autocomplete="off" name="radio_NGNEPQIQJN" value="x"><span>A non-significant relationship.</span></label><label><input type="radio" autocomplete="off" name="radio_NGNEPQIQJN" value="answer"><span>A strong, negative monotonic relationship.</span></label>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-24-contents" aria-controls="callout-24" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Explain this answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-24" class="callout-24-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>“A strong, negative monotonic relationship.”</strong> is the correct answer. The value of .729 indicates a strong relationship and the minus indicates it is negative. For Spearman the relationship has to be monotonic.</p>
<p><strong>The other options are incorrect:</strong></p>
<ul>
<li><p><strong>“A strong, positive monotonic relationship”</strong> is incorrect because the minus implies the relationship is negative, not positive.</p></li>
<li><p><strong>“A strong, negative linear relationship”</strong> is incorrect because Spearman measures monotonic relationships, not linear ones.</p></li>
<li><p><strong>“A non-significant relationship”</strong> is incorrect because the question does not state the p-value or provide sample size information. Hence, we cannot assume anything about significance. For example, small samples with large rho (or r) values may not be statistically significant. Contrastingly, in large samples, smaller rho (or r) values can be significant.</p></li>
</ul>
</div>
</div>
</div>


</section></section></main><!-- /main --><script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  var t = document.getElementsByClassName("webex-total_correct");
  for (var i = 0; i < t.length; i++) {
    p = t[i].parentElement;
    var correct = p.getElementsByClassName("webex-correct").length;
    var solvemes = p.getElementsByClassName("webex-solveme").length;
    var radiogroups = p.getElementsByClassName("webex-radiogroup").length;
    var selects = p.getElementsByClassName("webex-select").length;

    t[i].innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");

  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* check answers */
check_func = function() {
  console.log("webex: check answers");

  var cl = this.parentElement.classList;
  if (cl.contains('unchecked')) {
    cl.remove("unchecked");
    this.innerHTML = "Hide Answers";
  } else {
    cl.add("unchecked");
    this.innerHTML = "Show Answers";
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");

  var cl = this.classList

  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;

  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }

  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

window.onload = function() {
  console.log("webex onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  var check_sections = document.getElementsByClassName("webex-check");
  console.log("check:", check_sections.length);
  for (var i = 0; i < check_sections.length; i++) {
    check_sections[i].classList.add("unchecked");

    let btn = document.createElement("button");
    btn.innerHTML = "Show Answers";
    btn.classList.add("webex-check-button");
    btn.onclick = check_func;
    check_sections[i].appendChild(btn);

    let spn = document.createElement("span");
    spn.classList.add("webex-total_correct");
    check_sections[i].appendChild(spn);
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;

    solveme[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }

  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
    selects[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  update_total_correct();
}

</script><script>
// open rdrr links externally ----

var exlinks = document.querySelectorAll("a[href^='https://rdrr.io']");
var exlink_func = function(){
  window.open(this.href);
  return false;
};
for (var i = 0; i < exlinks.length; i++) {
    exlinks[i].addEventListener('click', exlink_func, false);
}

// visible second sidebar in mobile ----

function move_sidebar() {
  var toc = document.getElementById("TOC");
  var small_sidebar = document.querySelector("#quarto-sidebar .sidebar-menu-container");
  var right_sidebar = document.getElementById("quarto-margin-sidebar");

  if (window.innerWidth < 768) {
    small_sidebar.append(toc);
  } else {
    right_sidebar.append(toc);
  }
}
move_sidebar();
window.onresize = move_sidebar;
</script><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./08-paired.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Paired t-test</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./10-regression.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Simple regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">CC-BY (2024) Gaby Mahrholz Carolina E. Kuepper-Tetzel</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>


</body></html>